/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Constant identifier surfaced to the TS loader so it can verify
 * it's loading a compatible binding.
 */
export declare function bindingVersion(): string

/**
 * Structural diff of two JSON values (received as JSON strings
 * since napi-rs's JsUnknown is awkward to walk). Returns a JSON
 * string of the delta list.
 *
 * TS-side wrapper parses both directions so callers see a
 * typed `ArgDelta[]` matching the pure-TS surface exactly.
 */
export declare function toolArgDeltaJson(aJson: string, bJson: string): string

/**
 * Levenshtein edit distance between two flat string sequences,
 * normalised to `[0.0, 1.0]` by the longer length. Identical to
 * `shadow_align::trajectory_distance` in pure Rust.
 */
export declare function trajectoryDistance(a: Array<string>, b: Array<string>): number
