"""GitHub PR-comment flavoured markdown (collapsible CDFs etc.)."""

from __future__ import annotations

from typing import Any

from shadow.report.markdown import render_markdown


def render_github_pr(report: dict[str, Any]) -> str:
    """Produce a PR-friendly markdown comment.

    Wraps the basic markdown table with a collapsible `<details>` section
    for per-axis sample counts, a shadow branding line, and a footer
    link placeholder. Ready to post via `gh pr comment`.
    """
    base = render_markdown(report)
    details_lines = ["<details>", "<summary>Per-axis sample counts</summary>", ""]
    details_lines.append("| axis | n |")
    details_lines.append("|------|---:|")
    for row in report.get("rows", []):
        details_lines.append(f"| {row.get('axis', '')} | {row.get('n', 0)} |")
    details_lines.append("</details>")
    details_lines.append("")
    details_lines.append("_Generated by [Shadow](https://github.com/shadow-dev/shadow)._")
    return base + "\n" + "\n".join(details_lines) + "\n"
