"""Tests for Recommendation rendering across all three report formats.

The `recommendations` field is produced by the Rust core (see
`crates/shadow-core/src/diff/recommendations.rs`). These tests verify
each Python renderer surfaces the field correctly and, when absent,
falls back gracefully.
"""

from __future__ import annotations

from io import StringIO
from typing import Any

from rich.console import Console

from shadow.report.github_pr import render_github_pr
from shadow.report.markdown import render_markdown
from shadow.report.terminal import render_terminal


def _axes_row(axis: str) -> dict[str, Any]:
    return {
        "axis": axis,
        "baseline_median": 1.0,
        "candidate_median": 0.8,
        "delta": -0.2,
        "ci95_low": -0.3,
        "ci95_high": -0.1,
        "severity": "moderate",
        "n": 10,
        "flags": [],
    }


def _report(recommendations: list[dict[str, Any]] | None = None) -> dict[str, Any]:
    return {
        "rows": [_axes_row(a) for a in ("semantic", "trajectory", "safety")],
        "baseline_trace_id": "sha256:aaa",
        "candidate_trace_id": "sha256:bbb",
        "pair_count": 3,
        "first_divergence": None,
        "divergences": [],
        "recommendations": recommendations or [],
    }


def _rec(
    severity: str = "error",
    action: str = "restore",
    turn: int = 3,
    message: str = "Restore `send_confirmation_email` at turn 3.",
    rationale: str = "candidate dropped tool call(s): `send_confirmation_email(to)`",
) -> dict[str, Any]:
    return {
        "severity": severity,
        "action": action,
        "turn": turn,
        "message": message,
        "rationale": rationale,
        "axis": "trajectory",
        "confidence": 0.82,
    }


# ---------------------------------------------------------------------------
# markdown
# ---------------------------------------------------------------------------


def test_markdown_renders_recommendations_section_when_present() -> None:
    md = render_markdown(_report([_rec()]))
    assert "### Recommendations" in md
    assert "error" in md
    assert "RESTORE" in md
    assert "Restore `send_confirmation_email`" in md
    assert "send_confirmation_email(to)" in md  # rationale


def test_markdown_omits_recommendations_when_empty() -> None:
    md = render_markdown(_report([]))
    assert "Recommendations" not in md
    # Base axis table still renders
    assert "| semantic |" in md


def test_markdown_renders_all_three_severity_levels() -> None:
    recs = [
        _rec(severity="error", action="restore", message="Restore X."),
        _rec(severity="warning", action="revert", message="Revert Y."),
        _rec(severity="info", action="verify", message="Verify Z."),
    ]
    md = render_markdown(_report(recs))
    assert "error" in md and "RESTORE" in md
    assert "warning" in md and "REVERT" in md
    assert "info" in md and "VERIFY" in md
    # Severity icons surface as well
    assert "🔴" in md
    assert "🟡" in md
    assert "🔵" in md


# ---------------------------------------------------------------------------
# terminal
# ---------------------------------------------------------------------------


def test_terminal_renders_recommendations_when_present() -> None:
    buf = StringIO()
    console = Console(file=buf, force_terminal=False, width=200)
    render_terminal(_report([_rec()]), console=console)
    out = buf.getvalue()
    assert "recommendations" in out
    assert "error" in out
    assert "RESTORE" in out
    assert "Restore `send_confirmation_email`" in out


def test_terminal_omits_recommendations_when_empty() -> None:
    buf = StringIO()
    console = Console(file=buf, force_terminal=False, width=200)
    render_terminal(_report([]), console=console)
    out = buf.getvalue()
    assert "recommendations" not in out


def test_terminal_renders_multiple_recommendations_with_counts() -> None:
    recs = [_rec(turn=i, message=f"Fix at turn {i}.") for i in range(4)]
    buf = StringIO()
    console = Console(file=buf, force_terminal=False, width=200)
    render_terminal(_report(recs), console=console)
    out = buf.getvalue()
    assert "recommendations (4)" in out
    for i in range(4):
        assert f"Fix at turn {i}" in out


# ---------------------------------------------------------------------------
# github-pr (inherits from markdown)
# ---------------------------------------------------------------------------


def test_github_pr_inherits_recommendations_section() -> None:
    pr = render_github_pr(_report([_rec()]))
    assert "Recommendations" in pr
    assert "RESTORE" in pr
    # Footer + per-axis counts still present
    assert "<details>" in pr
    assert "Generated by" in pr


# ---------------------------------------------------------------------------
# Integration: real Rust-generated output flows through renderer
# ---------------------------------------------------------------------------


def test_rust_generated_recommendations_render_in_markdown() -> None:
    """End-to-end: build a trace pair with a known regression, call the
    Rust diff + generate pipeline, and verify the recommendation flows
    into the markdown renderer."""
    from shadow import _core

    def mk_meta() -> dict[str, Any]:
        p = {"sdk": {"name": "shadow"}}
        return {
            "version": "0.1",
            "id": _core.content_id(p),
            "kind": "metadata",
            "ts": "2026-04-23T10:00:00Z",
            "parent": None,
            "payload": p,
        }

    def mk_resp(content: list[dict[str, Any]], stop: str = "end_turn") -> dict[str, Any]:
        p = {
            "model": "x",
            "content": content,
            "stop_reason": stop,
            "latency_ms": 0,
            "usage": {"input_tokens": 1, "output_tokens": 1, "thinking_tokens": 0},
        }
        return {
            "version": "0.1",
            "id": _core.content_id(p),
            "kind": "chat_response",
            "ts": "2026-04-23T10:00:00Z",
            "parent": None,
            "payload": p,
        }

    baseline = [
        mk_meta(),
        mk_resp(
            [{"type": "tool_use", "id": "t1", "name": "send_email", "input": {"to": "x"}}],
            stop="tool_use",
        ),
    ]
    # Candidate drops the tool call entirely
    candidate = [mk_meta(), mk_resp([{"type": "text", "text": "done"}])]
    report = _core.compute_diff_report(baseline, candidate)
    md = render_markdown(report)
    assert "Recommendations" in md
    assert "RESTORE" in md
    assert "send_email" in md
