"""Tests for first-divergence rendering across all three report formats.

The `first_divergence` field is produced by the Rust core (see
`crates/shadow-core/src/diff/alignment.rs`). These tests verify that
each Python renderer surfaces the field correctly and, when absent,
falls back to the original format.
"""

from __future__ import annotations

from io import StringIO
from typing import Any

from rich.console import Console

from shadow.report.github_pr import render_github_pr
from shadow.report.markdown import render_markdown
from shadow.report.terminal import render_terminal


def _axes_row(axis: str) -> dict[str, Any]:
    return {
        "axis": axis,
        "baseline_median": 1.0,
        "candidate_median": 0.8,
        "delta": -0.2,
        "ci95_low": -0.3,
        "ci95_high": -0.1,
        "severity": "moderate",
        "n": 10,
        "flags": [],
    }


def _report(first_divergence: dict[str, Any] | None) -> dict[str, Any]:
    return {
        "rows": [_axes_row(a) for a in ("semantic", "trajectory", "safety")],
        "baseline_trace_id": "sha256:aaa",
        "candidate_trace_id": "sha256:bbb",
        "pair_count": 3,
        "first_divergence": first_divergence,
    }


def test_markdown_renders_first_divergence_when_present() -> None:
    fd = {
        "baseline_turn": 2,
        "candidate_turn": 2,
        "kind": "structural_drift",
        "primary_axis": "trajectory",
        "explanation": "candidate added tool call(s): `search(limit,q)`",
        "confidence": 0.72,
    }
    md = render_markdown(_report(fd))
    assert "First divergence" in md
    assert "#2" in md
    assert "structural_drift" in md
    # v3.0+ uses plain-English axis labels ("tool calls" instead of
    # the internal "trajectory" name).
    assert "tool calls" in md
    assert "72%" in md
    assert "search(limit,q)" in md


def test_markdown_omits_first_divergence_when_absent() -> None:
    md = render_markdown(_report(None))
    assert "First divergence" not in md
    # Base table still renders, with v3.0+ plain-English axis labels.
    assert "| response meaning |" in md
    assert "Worst severity" in md


def test_terminal_renders_first_divergence_when_present() -> None:
    fd = {
        "baseline_turn": 0,
        "candidate_turn": 0,
        "kind": "decision_drift",
        "primary_axis": "safety",
        "explanation": "stop_reason changed: `end_turn` → `content_filter`",
        "confidence": 0.85,
    }
    buf = StringIO()
    console = Console(file=buf, force_terminal=False, width=200)
    render_terminal(_report(fd), console=console)
    out = buf.getvalue()
    assert "first divergence" in out
    assert "decision_drift" in out
    # v3.0+ uses plain-English axis labels ("refusals" not "safety").
    assert "refusals" in out
    assert "85%" in out
    assert "stop_reason" in out


def test_terminal_omits_first_divergence_when_absent() -> None:
    buf = StringIO()
    console = Console(file=buf, force_terminal=False, width=200)
    render_terminal(_report(None), console=console)
    out = buf.getvalue()
    assert "first divergence" not in out
    assert "worst severity" in out


def test_github_pr_inherits_first_divergence_section() -> None:
    """v3.0+ github-pr renderer surfaces divergences as turn-level prose
    under 'What changed at the turn level' rather than reusing the
    markdown 'First divergence' section verbatim. The explanation
    text + turn references still survive."""
    fd = {
        "baseline_turn": 4,
        "candidate_turn": 3,
        "kind": "style_drift",
        "primary_axis": "semantic",
        "explanation": "cosmetic wording change — tool sequence preserved",
        "confidence": 0.55,
    }
    pr = render_github_pr(_report(fd))
    assert "What changed at the turn level" in pr
    # Turn references survive (e.g. "Turn 3" for the candidate side).
    assert "Turn 3" in pr
    # Explanation prose surfaces verbatim.
    assert "cosmetic wording change" in pr
    # Numbers section is collapsed into a fold + footer.
    assert "<details>" in pr
    assert "Generated by" in pr


def _divergence(
    kind: str = "structural_drift",
    axis: str = "trajectory",
    baseline_turn: int = 0,
    candidate_turn: int = 0,
    confidence: float = 0.6,
    explanation: str = "example",
) -> dict[str, Any]:
    return {
        "baseline_turn": baseline_turn,
        "candidate_turn": candidate_turn,
        "kind": kind,
        "primary_axis": axis,
        "explanation": explanation,
        "confidence": confidence,
    }


def test_markdown_top_k_renders_all_three_ranked() -> None:
    """Markdown should show rank labels `#1 of 3`, `#2 of 3`, `#3 of 3`
    when exactly 3 divergences exist."""
    divs = [
        _divergence(kind="structural_drift", axis="trajectory", baseline_turn=0, confidence=0.56),
        _divergence(kind="decision_drift", axis="safety", baseline_turn=2, confidence=0.32),
        _divergence(kind="decision_drift", axis="semantic", baseline_turn=1, confidence=0.15),
    ]
    report = _report(divs[0])
    report["divergences"] = divs
    md = render_markdown(report)
    assert "Top divergences" in md
    assert "#1 of 3" in md
    assert "#2 of 3" in md
    assert "#3 of 3" in md


def test_markdown_top_k_puts_extras_in_collapsible_details() -> None:
    """With >3 divergences, only the top 3 show inline; the rest go
    inside `<details>`."""
    divs = [_divergence(baseline_turn=i, confidence=0.5 - i * 0.05) for i in range(5)]
    report = _report(divs[0])
    report["divergences"] = divs
    md = render_markdown(report)
    assert "<details>" in md
    assert "+2 more" in md
    assert "ranks 4-5" in md
    assert "#4 of 5" in md
    assert "#5 of 5" in md


def test_markdown_top_k_one_divergence_uses_first_divergence_header() -> None:
    """With a single divergence, we keep the older 'First divergence'
    header instead of 'Top divergences' to match the pre-top-K UX."""
    divs = [_divergence(baseline_turn=0, confidence=0.7)]
    report = _report(divs[0])
    report["divergences"] = divs
    md = render_markdown(report)
    assert "First divergence" in md
    assert "Top divergences" not in md


def test_terminal_shows_ranks_when_multiple_divergences() -> None:
    divs = [
        _divergence(kind="structural_drift", baseline_turn=0, confidence=0.8),
        _divergence(kind="decision_drift", baseline_turn=1, confidence=0.5),
    ]
    report = _report(divs[0])
    report["divergences"] = divs
    buf = StringIO()
    console = Console(file=buf, force_terminal=False, width=200)
    render_terminal(report, console=console)
    out = buf.getvalue()
    assert "top divergences" in out
    assert "#1" in out
    assert "#2" in out
    assert "structural_drift" in out
    assert "decision_drift" in out


def test_github_pr_inherits_top_k_rendering() -> None:
    """v3.0+ surfaces multiple divergences as a 'What changed at the
    turn level' bullet list (top 3 inline, rest folded as 'and N more').
    The 'Top divergences' header is no longer used in the github-pr
    renderer — that wording lives in the older markdown renderer
    (and the asserted bullets still capture the data)."""
    divs = [
        _divergence(kind="structural_drift", baseline_turn=0, candidate_turn=0, confidence=0.8),
        _divergence(kind="decision_drift", baseline_turn=1, candidate_turn=2, confidence=0.5),
    ]
    report = _report(divs[0])
    report["divergences"] = divs
    pr = render_github_pr(report)
    assert "What changed at the turn level" in pr
    # Both divergences appear as bullets with their candidate turn numbers.
    assert "Turn 0" in pr
    assert "Turn 2" in pr
    # Envelope still present.
    assert "<details>" in pr
    assert "Generated by" in pr


def test_all_three_divergence_kinds_render_cleanly() -> None:
    for kind, axis, explanation in [
        ("style_drift", "semantic", "cosmetic wording change"),
        ("decision_drift", "trajectory", "tool arg value changed: `limit`: `10` → `50`"),
        ("structural_drift", "trajectory", "candidate added tool call(s): `search(q)`"),
    ]:
        fd = {
            "baseline_turn": 1,
            "candidate_turn": 1,
            "kind": kind,
            "primary_axis": axis,
            "explanation": explanation,
            "confidence": 0.6,
        }
        md = render_markdown(_report(fd))
        assert kind in md
        assert axis in md

        buf = StringIO()
        console = Console(file=buf, force_terminal=False, width=200)
        render_terminal(_report(fd), console=console)
        assert kind in buf.getvalue()
