"""Tests for first-divergence rendering across all three report formats.

The `first_divergence` field is produced by the Rust core (see
`crates/shadow-core/src/diff/alignment.rs`). These tests verify that
each Python renderer surfaces the field correctly and, when absent,
falls back to the original format.
"""

from __future__ import annotations

from io import StringIO
from typing import Any

from rich.console import Console

from shadow.report.github_pr import render_github_pr
from shadow.report.markdown import render_markdown
from shadow.report.terminal import render_terminal


def _axes_row(axis: str) -> dict[str, Any]:
    return {
        "axis": axis,
        "baseline_median": 1.0,
        "candidate_median": 0.8,
        "delta": -0.2,
        "ci95_low": -0.3,
        "ci95_high": -0.1,
        "severity": "moderate",
        "n": 10,
        "flags": [],
    }


def _report(first_divergence: dict[str, Any] | None) -> dict[str, Any]:
    return {
        "rows": [_axes_row(a) for a in ("semantic", "trajectory", "safety")],
        "baseline_trace_id": "sha256:aaa",
        "candidate_trace_id": "sha256:bbb",
        "pair_count": 3,
        "first_divergence": first_divergence,
    }


def test_markdown_renders_first_divergence_when_present() -> None:
    fd = {
        "baseline_turn": 2,
        "candidate_turn": 2,
        "kind": "structural_drift",
        "primary_axis": "trajectory",
        "explanation": "candidate added tool call(s): `search(limit,q)`",
        "confidence": 0.72,
    }
    md = render_markdown(_report(fd))
    assert "First divergence" in md
    assert "#2" in md
    assert "structural_drift" in md
    assert "trajectory" in md
    assert "72%" in md
    assert "search(limit,q)" in md


def test_markdown_omits_first_divergence_when_absent() -> None:
    md = render_markdown(_report(None))
    assert "First divergence" not in md
    # Base table still renders
    assert "| semantic |" in md
    assert "Worst severity" in md


def test_terminal_renders_first_divergence_when_present() -> None:
    fd = {
        "baseline_turn": 0,
        "candidate_turn": 0,
        "kind": "decision_drift",
        "primary_axis": "safety",
        "explanation": "stop_reason changed: `end_turn` → `content_filter`",
        "confidence": 0.85,
    }
    buf = StringIO()
    console = Console(file=buf, force_terminal=False, width=200)
    render_terminal(_report(fd), console=console)
    out = buf.getvalue()
    assert "first divergence" in out
    assert "decision_drift" in out
    assert "safety" in out
    assert "85%" in out
    assert "stop_reason" in out


def test_terminal_omits_first_divergence_when_absent() -> None:
    buf = StringIO()
    console = Console(file=buf, force_terminal=False, width=200)
    render_terminal(_report(None), console=console)
    out = buf.getvalue()
    assert "first divergence" not in out
    assert "worst severity" in out


def test_github_pr_inherits_first_divergence_section() -> None:
    fd = {
        "baseline_turn": 4,
        "candidate_turn": 3,
        "kind": "style_drift",
        "primary_axis": "semantic",
        "explanation": "cosmetic wording change — tool sequence preserved",
        "confidence": 0.55,
    }
    pr = render_github_pr(_report(fd))
    # Shows the first-divergence section (from the underlying markdown)
    assert "First divergence" in pr
    assert "style_drift" in pr
    # Plus the GH PR envelope: collapsible details + footer link
    assert "<details>" in pr
    assert "Per-axis sample counts" in pr
    assert "Generated by" in pr


def test_all_three_divergence_kinds_render_cleanly() -> None:
    for kind, axis, explanation in [
        ("style_drift", "semantic", "cosmetic wording change"),
        ("decision_drift", "trajectory", "tool arg value changed: `limit`: `10` → `50`"),
        ("structural_drift", "trajectory", "candidate added tool call(s): `search(q)`"),
    ]:
        fd = {
            "baseline_turn": 1,
            "candidate_turn": 1,
            "kind": kind,
            "primary_axis": axis,
            "explanation": explanation,
            "confidence": 0.6,
        }
        md = render_markdown(_report(fd))
        assert kind in md
        assert axis in md

        buf = StringIO()
        console = Console(file=buf, force_terminal=False, width=200)
        render_terminal(_report(fd), console=console)
        assert kind in buf.getvalue()
