"""Typer-based CLI for shadow."""

from __future__ import annotations

import asyncio
import json
import os
import subprocess
import sys
from enum import StrEnum
from pathlib import Path
from typing import Annotated, Any

import typer
import yaml
from rich.console import Console

from shadow import __version__, _core
from shadow.errors import ShadowError

app = typer.Typer(
    name="shadow",
    help="Git-native behavioral diff and shadow deployment for LLM agents.",
    no_args_is_help=True,
    add_completion=False,
)

console = Console(stderr=False)
err_console = Console(stderr=True)


# ---- init ------------------------------------------------------------------

DEFAULT_CONFIG_TOML = """# .shadow/config.toml — generated by `shadow init`.
# See SPEC.md §8 for what this controls.

[store]
# Where traces and the SQLite index live, relative to the repo root.
path = ".shadow"

[replay]
# Default backend when `--backend` is not specified.
default_backend = "mock"
"""


@app.command()
def init(
    path: Annotated[Path, typer.Argument(help="Project root (defaults to cwd)")] = Path("."),
) -> None:
    """Scaffold `.shadow/` in PATH. Creates dirs, config.toml, sqlite index."""
    try:
        shadow_dir = path / ".shadow"
        (shadow_dir / "traces").mkdir(parents=True, exist_ok=True)
        (shadow_dir / "replays").mkdir(parents=True, exist_ok=True)
        (shadow_dir / "cache").mkdir(parents=True, exist_ok=True)
        config_path = shadow_dir / "config.toml"
        if not config_path.exists():
            config_path.write_text(DEFAULT_CONFIG_TOML)
        err_console.print(f"[green]✓[/] initialised shadow store at {shadow_dir}")
    except Exception as e:
        _fail(e)


# ---- record ----------------------------------------------------------------


@app.command()
def record(
    ctx: typer.Context,
    output: Annotated[
        Path, typer.Option("--output", "-o", help="Where to write the .agentlog file")
    ] = Path("recording.agentlog"),
) -> None:
    """Run a subcommand with SHADOW_SESSION_OUTPUT pointing at OUTPUT.

    Example:
        shadow record -o demo.agentlog -- python agent.py

    The wrapped command is expected to use shadow.sdk.Session for
    recording; if it doesn't, this command is a no-op (exits with the
    child's exit code).
    """
    args = ctx.args
    if not args:
        err_console.print("[red]error[/]: specify a command after `--`")
        raise typer.Exit(code=2)
    env = dict(os.environ)
    env["SHADOW_SESSION_OUTPUT"] = str(output.resolve())
    result = subprocess.run(args, env=env, check=False)
    raise typer.Exit(code=result.returncode)


# allow `shadow record -- python agent.py` (trailing args)
# typer picks up ctx.args when the command is declared with allow_extra_args
app.info.context_settings = {"allow_extra_args": True, "ignore_unknown_options": True}


# ---- replay ----------------------------------------------------------------


class BackendKind(StrEnum):
    """Supported replay backends."""

    mock = "mock"
    positional = "positional"


@app.command()
def replay(
    config_path: Annotated[Path, typer.Argument(help="Candidate config YAML")],
    baseline: Annotated[Path, typer.Option("--baseline", help="Baseline .agentlog file")],
    backend: Annotated[
        BackendKind, typer.Option("--backend", help="Backend to use")
    ] = BackendKind.mock,
    reference: Annotated[
        Path | None,
        typer.Option(
            "--reference",
            help="(positional backend only) candidate-recording to replay from",
        ),
    ] = None,
    output: Annotated[
        Path | None, typer.Option("--output", "-o", help="Where to write the candidate .agentlog")
    ] = None,
) -> None:
    """Replay BASELINE's requests through BACKEND, writing a candidate trace."""
    from shadow.llm import MockLLM, PositionalMockLLM
    from shadow.replay import run_replay

    try:
        # Validate the config is readable YAML (not used by Rust core in v0.1;
        # config-driven behavior-change lives in the candidate fixture/backend).
        yaml.safe_load(config_path.read_text())

        baseline_records = _core.parse_agentlog(baseline.read_bytes())
        if backend is BackendKind.mock:
            bk: Any = MockLLM.from_trace(baseline_records)
        else:
            if reference is None:
                err_console.print("[red]error[/]: --backend positional requires --reference <path>")
                raise typer.Exit(code=2)
            bk = PositionalMockLLM.from_path(reference)
        candidate = asyncio.run(run_replay(baseline_records, bk))
        out_path = output or _default_replay_output()
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_bytes(_core.write_agentlog(candidate))
        err_console.print(f"[green]✓[/] replay written to {out_path} ({len(candidate)} records)")
    except ShadowError as e:
        _fail(e)
    except typer.Exit:
        raise
    except Exception as e:
        _fail(e)


def _default_replay_output() -> Path:
    return Path(".shadow/replays/latest.agentlog")


# ---- diff ------------------------------------------------------------------


class SemanticMode(StrEnum):
    """Semantic-axis backend for `shadow diff --semantic`."""

    bm25 = "bm25"
    embeddings = "embeddings"


class JudgeKind(StrEnum):
    """Judges available for the `diff --judge` flag."""

    none = "none"
    sanity = "sanity"


class JudgeBackend(StrEnum):
    """LLM backends the SanityJudge can run against."""

    mock = "mock"
    anthropic = "anthropic"
    openai = "openai"


@app.command("diff")
def diff_cmd(
    baseline: Annotated[Path, typer.Argument(help="Baseline .agentlog file")],
    candidate: Annotated[Path, typer.Argument(help="Candidate .agentlog file")],
    pricing: Annotated[
        Path | None,
        typer.Option("--pricing", help="JSON pricing file (dict model→[in,out] USD/token)"),
    ] = None,
    seed: Annotated[int, typer.Option("--seed", help="RNG seed for bootstrap")] = 42,
    output_json: Annotated[
        Path | None,
        typer.Option("--output-json", help="Write DiffReport JSON to this path"),
    ] = None,
    semantic: Annotated[
        SemanticMode,
        typer.Option(
            "--semantic",
            help="Semantic-axis backend. `bm25` (default) = TF-IDF cosine; "
            "`embeddings` = sentence-transformers/all-MiniLM-L6-v2 (requires [embeddings] extra).",
        ),
    ] = SemanticMode.bm25,
    judge: Annotated[
        JudgeKind,
        typer.Option(
            "--judge",
            help="Populate axis 8 with a judge. `sanity` uses a domain-agnostic A/B prompt.",
        ),
    ] = JudgeKind.none,
    judge_backend: Annotated[
        JudgeBackend,
        typer.Option("--judge-backend", help="LLM backend the judge runs against"),
    ] = JudgeBackend.mock,
    judge_model: Annotated[
        str | None,
        typer.Option("--judge-model", help="Override the model name the judge uses"),
    ] = None,
) -> None:
    """Compute a nine-axis diff between two traces and print the report."""
    from shadow.report import render_terminal

    try:
        b = _core.parse_agentlog(baseline.read_bytes())
        c = _core.parse_agentlog(candidate.read_bytes())
        price_map: dict[str, tuple[float, float]] | None = None
        if pricing is not None:
            raw = json.loads(pricing.read_text())
            price_map = _parse_pricing_table(raw)
        report = _core.compute_diff_report(b, c, price_map, seed)
        if semantic is SemanticMode.embeddings:
            report = _apply_embeddings_semantic(report, baseline=b, candidate=c, seed=seed)
        if judge is not JudgeKind.none:
            report = _apply_judge(
                report,
                baseline_records=b,
                candidate_records=c,
                judge_kind=judge,
                judge_backend=judge_backend,
                judge_model=judge_model,
                seed=seed,
            )
        render_terminal(report, console=console)
        if output_json is not None:
            output_json.parent.mkdir(parents=True, exist_ok=True)
            output_json.write_text(json.dumps(report, indent=2))
    except ShadowError as e:
        _fail(e)
    except Exception as e:
        _fail(e)


def _parse_pricing_table(raw: dict[str, Any]) -> dict[str, Any]:
    """Accept either legacy [input, output] tuple form or rich dict form.

    Rich form:
        "claude-opus-4-7": {
            "input": 0.000015,
            "output": 0.000075,
            "cached_input": 0.0000015,
            "reasoning": 0.0,
            "batch_discount": 0.5
        }
    """
    out: dict[str, Any] = {}
    for model, value in raw.items():
        if isinstance(value, list | tuple) and len(value) == 2:
            out[model] = (float(value[0]), float(value[1]))
        elif isinstance(value, dict):
            out[model] = {
                "input": float(value.get("input", 0.0)),
                "output": float(value.get("output", 0.0)),
                "cached_input": float(value.get("cached_input", 0.0)),
                "cached_write_5m": float(value.get("cached_write_5m", 0.0)),
                "cached_write_1h": float(value.get("cached_write_1h", 0.0)),
                "reasoning": float(value.get("reasoning", 0.0)),
                "batch_discount": float(value.get("batch_discount", 0.0)),
            }
        else:
            raise ShadowError(f"pricing entry for {model!r} must be [input, output] or a dict")
    return out


def _apply_embeddings_semantic(
    report: dict[str, Any],
    *,
    baseline: list[dict[str, Any]],
    candidate: list[dict[str, Any]],
    seed: int,
) -> dict[str, Any]:
    """Swap axis 1 (semantic) with a real sentence-transformer result."""
    try:
        from shadow.embeddings import SemanticEmbedder, recompute_semantic_axis
    except ImportError:
        err_console.print(
            "[yellow]warning[/]: --semantic embeddings requested but "
            "`shadow[embeddings]` isn't installed; falling back to BM25."
        )
        return report
    try:
        embedder = SemanticEmbedder()
    except ShadowError as e:
        err_console.print(f"[yellow]warning[/]: {e}; falling back to BM25.")
        return report
    new_row = recompute_semantic_axis(baseline, candidate, embedder, seed=seed)
    new_rows = [new_row if r.get("axis") == "semantic" else r for r in report.get("rows", [])]
    return {**report, "rows": new_rows}


def _apply_judge(
    report: dict[str, Any],
    *,
    baseline_records: list[dict[str, Any]],
    candidate_records: list[dict[str, Any]],
    judge_kind: JudgeKind,
    judge_backend: JudgeBackend,
    judge_model: str | None,
    seed: int,
) -> dict[str, Any]:
    from shadow.judge import SanityJudge, aggregate_scores
    from shadow.llm import get_backend

    if judge_kind is not JudgeKind.sanity:
        return report

    pairs = _pair_responses(baseline_records, candidate_records)
    if not pairs:
        return report

    backend = get_backend(judge_backend.value)
    sanity = SanityJudge(backend, model=judge_model)

    async def _run() -> list[float]:
        out: list[float] = []
        for b_resp, c_resp, req_ctx in pairs:
            verdict = await sanity.score_pair(b_resp, c_resp, req_ctx)
            out.append(verdict["score"])
        return out

    scores = asyncio.run(_run())
    new_row = aggregate_scores(scores, seed=seed)
    new_rows = [new_row if r.get("axis") == "judge" else r for r in report.get("rows", [])]
    return {**report, "rows": new_rows}


def _pair_responses(
    baseline_records: list[dict[str, Any]],
    candidate_records: list[dict[str, Any]],
) -> list[tuple[dict[str, Any], dict[str, Any], dict[str, Any] | None]]:
    """Pair the i-th chat_response from baseline with the i-th from candidate.

    Each tuple also carries the baseline chat_request that preceded it (if
    any) so the judge has task context.
    """
    b_resps: list[dict[str, Any]] = []
    b_reqs_before: list[dict[str, Any] | None] = []
    last_req: dict[str, Any] | None = None
    for r in baseline_records:
        kind = r.get("kind")
        if kind == "chat_request":
            last_req = r.get("payload")
        elif kind == "chat_response":
            b_resps.append(r.get("payload") or {})
            b_reqs_before.append(last_req)
    c_resps: list[dict[str, Any]] = [
        r.get("payload") or {} for r in candidate_records if r.get("kind") == "chat_response"
    ]
    paired: list[tuple[dict[str, Any], dict[str, Any], dict[str, Any] | None]] = []
    for i in range(min(len(b_resps), len(c_resps))):
        paired.append((b_resps[i], c_resps[i], b_reqs_before[i]))
    return paired


# ---- bisect ----------------------------------------------------------------


class BisectBackend(StrEnum):
    """Backends available for live-replay corner bisection."""

    none = "none"
    anthropic = "anthropic"
    openai = "openai"
    positional = "positional"


@app.command()
def bisect(
    config_a: Annotated[Path, typer.Argument(help="Baseline config YAML")],
    config_b: Annotated[Path, typer.Argument(help="Candidate config YAML")],
    traces: Annotated[Path, typer.Option("--traces", help="Baseline .agentlog trace or dir")],
    candidate_traces: Annotated[
        Path | None,
        typer.Option(
            "--candidate-traces",
            help=(
                "Candidate .agentlog trace recorded under config_b. Used for "
                "the heuristic allocator when --backend is none."
            ),
        ),
    ] = None,
    backend: Annotated[
        BisectBackend,
        typer.Option(
            "--backend",
            help=(
                "Live backend for LASSO-over-corners scoring. 'anthropic' / "
                "'openai' require the corresponding extras and an API key. "
                "'positional' replays from a reference trace. 'none' falls "
                "back to --candidate-traces heuristic."
            ),
        ),
    ] = BisectBackend.none,
    reference: Annotated[
        Path | None,
        typer.Option(
            "--reference",
            help="(positional backend only) reference .agentlog for replay.",
        ),
    ] = None,
    output_json: Annotated[
        Path | None, typer.Option("--output-json", help="Write attribution JSON here")
    ] = None,
) -> None:
    """Rank which atomic config deltas caused which behavioral axes to move."""
    try:
        from shadow.bisect import run_bisect
    except ImportError as e:
        _fail(
            Exception(
                f"shadow.bisect failed to import ({e}); install with `pip install shadow[dev]`"
            )
        )
        return

    live_backend = None
    if backend is not BisectBackend.none:
        from shadow.llm import get_backend

        kwargs: dict[str, Any] = {}
        if backend is BisectBackend.positional:
            if reference is None:
                err_console.print("[red]error[/]: --backend positional requires --reference <path>")
                raise typer.Exit(code=2)
            kwargs["reference_path"] = reference
        try:
            live_backend = get_backend(backend.value, **kwargs)
        except ShadowError as e:
            _fail(e)
            return

    try:
        result = run_bisect(
            config_a,
            config_b,
            traces,
            candidate_traces=candidate_traces,
            backend=live_backend,
        )
        text = json.dumps(_json_safe(result), indent=2)
        if output_json is not None:
            output_json.parent.mkdir(parents=True, exist_ok=True)
            output_json.write_text(text)
        else:
            sys.stdout.write(text + "\n")
    except ShadowError as e:
        _fail(e)
    except Exception as e:
        _fail(e)


def _json_safe(obj: Any) -> Any:
    """Recursively strip non-JSON values from a dict (e.g. numpy arrays)."""
    import numpy as np

    if isinstance(obj, dict):
        return {k: _json_safe(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_json_safe(v) for v in obj]
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    if isinstance(obj, np.integer | np.floating):
        return obj.item()
    return obj


# ---- report ----------------------------------------------------------------


class ReportFormat(StrEnum):
    """Supported report render formats."""

    terminal = "terminal"
    markdown = "markdown"
    github_pr = "github-pr"


@app.command()
def report(
    input_json: Annotated[Path, typer.Argument(help="DiffReport JSON file")],
    fmt: Annotated[
        ReportFormat, typer.Option("--format", "-f", help="Output format")
    ] = ReportFormat.terminal,
) -> None:
    """Re-render a saved DiffReport JSON."""
    from shadow.report import render_github_pr, render_markdown, render_terminal

    try:
        data = json.loads(input_json.read_text())
        if fmt is ReportFormat.terminal:
            render_terminal(data, console=console)
        elif fmt is ReportFormat.markdown:
            sys.stdout.write(render_markdown(data))
        else:
            sys.stdout.write(render_github_pr(data))
    except Exception as e:
        _fail(e)


# ---- join -----------------------------------------------------------------


@app.command()
def join(
    inputs: Annotated[
        list[Path], typer.Argument(help="Input .agentlog files to merge", metavar="INPUTS...")
    ],
    output: Annotated[Path, typer.Option("--output", "-o", help="Merged output path")],
) -> None:
    """Merge multiple `.agentlog` files (one per Session) into one logical trace.

    Records must carry `meta.trace_id` so we can group them; Sessions
    started under the same `SHADOW_TRACE_ID` env var share one. Parent
    links across files are rewired so the merged log is a single DAG.
    """
    try:
        all_records: list[dict[str, Any]] = []
        for p in inputs:
            all_records.extend(_core.parse_agentlog(p.read_bytes()))
        merged = _merge_by_trace(all_records)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_bytes(_core.write_agentlog(merged))
        err_console.print(
            f"[green]✓[/] merged {len(inputs)} file(s), {len(merged)} records → {output}"
        )
    except Exception as e:
        _fail(e)


def _merge_by_trace(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Group by trace_id; chain parent-span records before their children."""
    by_trace: dict[str, list[dict[str, Any]]] = {}
    orphans: list[dict[str, Any]] = []
    for r in records:
        tid = (r.get("meta") or {}).get("trace_id")
        if tid is None:
            orphans.append(r)
        else:
            by_trace.setdefault(str(tid), []).append(r)
    out: list[dict[str, Any]] = []
    # Orphans first (no trace context), then per-trace groups in
    # arrival order to keep output deterministic.
    out.extend(orphans)
    for tid in sorted(by_trace.keys()):
        # Within a trace: sort by timestamp to preserve causality.
        group = sorted(by_trace[tid], key=lambda r: r.get("ts", ""))
        out.extend(group)
    return out


# ---- import ---------------------------------------------------------------


class ImportFormat(StrEnum):
    """Formats `shadow import` can read."""

    langfuse = "langfuse"
    braintrust = "braintrust"
    otel = "otel"
    langsmith = "langsmith"
    openai_evals = "openai-evals"


@app.command("import")
def import_cmd(
    source: Annotated[Path, typer.Argument(help="Foreign-format export file (.json or .jsonl)")],
    fmt: Annotated[
        ImportFormat,
        typer.Option("--format", "-f", help="Source format"),
    ],
    output: Annotated[Path, typer.Option("--output", "-o", help="Output .agentlog path")],
) -> None:
    """Convert a Langfuse or Braintrust export into a Shadow `.agentlog`.

    Turns Shadow's open spec into a bridge format: if you've already
    instrumented with another observability tool, `shadow import` lets
    you run Shadow's differ over traces you already have.
    """
    from shadow.importers import (
        braintrust_to_agentlog,
        langfuse_to_agentlog,
        langsmith_to_agentlog,
        openai_evals_to_agentlog,
        otel_to_agentlog,
    )

    try:
        text = source.read_text()
        if fmt is ImportFormat.langfuse:
            data = json.loads(text)
            records = langfuse_to_agentlog(data)
        elif fmt is ImportFormat.braintrust:
            rows = _parse_braintrust_input(text)
            records = braintrust_to_agentlog(rows)
        elif fmt is ImportFormat.otel:
            data = json.loads(text)
            records = otel_to_agentlog(data)
        elif fmt is ImportFormat.langsmith:
            data = json.loads(text)
            records = langsmith_to_agentlog(data)
        elif fmt is ImportFormat.openai_evals:
            rows = _parse_jsonl_or_array(text)
            records = openai_evals_to_agentlog(rows)
        else:  # pragma: no cover — enum is exhaustive
            raise ValueError(f"unknown import format: {fmt}")
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_bytes(_core.write_agentlog(records))
        err_console.print(
            f"[green]✓[/] imported {len(records)} records from {fmt.value} → {output}"
        )
    except ShadowError as e:
        _fail(e)
    except Exception as e:
        _fail(e)


def _parse_braintrust_input(text: str) -> list[dict[str, Any]]:
    """Braintrust exports may be a JSON array or JSONL. Accept either."""
    return _parse_jsonl_or_array(text, "Braintrust")


def _parse_jsonl_or_array(text: str, label: str = "input") -> list[dict[str, Any]]:
    """Accept either a JSON array or newline-delimited JSON."""
    stripped = text.lstrip()
    if stripped.startswith("["):
        parsed = json.loads(text)
        if not isinstance(parsed, list):
            raise ShadowError(f"{label} JSON input must be an array of rows")
        return parsed
    rows: list[dict[str, Any]] = []
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        rows.append(json.loads(line))
    return rows


# ---- export ---------------------------------------------------------------


class ExportFormat(StrEnum):
    """Formats `shadow export` can emit."""

    otel = "otel"


@app.command()
def export(
    trace: Annotated[Path, typer.Argument(help="Input .agentlog file")],
    fmt: Annotated[
        ExportFormat, typer.Option("--format", "-f", help="Output format")
    ] = ExportFormat.otel,
    output: Annotated[
        Path | None, typer.Option("--output", "-o", help="Write to file (else stdout)")
    ] = None,
) -> None:
    """Export a Shadow `.agentlog` to a standard observability format.

    Currently ships `otel` — OpenTelemetry OTLP/JSON using the GenAI
    semantic conventions. Pipe into `otel-cli` or post to any collector's
    `/v1/traces` endpoint.
    """
    from shadow.otel import agentlog_to_otel

    try:
        records = _core.parse_agentlog(trace.read_bytes())
        if fmt is ExportFormat.otel:
            result = agentlog_to_otel(records)
        else:
            raise ValueError(f"unknown export format: {fmt}")
        payload = json.dumps(result, indent=2)
        if output is not None:
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_text(payload)
        else:
            sys.stdout.write(payload + "\n")
    except Exception as e:
        _fail(e)


# ---- serve ----------------------------------------------------------------


@app.command()
def serve(
    root: Annotated[str, typer.Option("--root", help="Shadow root dir to tail")] = ".shadow",
    host: Annotated[str, typer.Option("--host", help="Listen host")] = "127.0.0.1",
    port: Annotated[int, typer.Option("--port", help="Listen port")] = 8765,
) -> None:
    """Start the live diff dashboard (requires `shadow[serve]` extra)."""
    try:
        from shadow.serve import serve as _serve

        _serve(root=Path(root), host=host, port=port)
    except Exception as e:
        _fail(e)


# ---- schema-watch ---------------------------------------------------------


class SchemaWatchFormat(StrEnum):
    """Output formats for `shadow schema-watch`."""

    terminal = "terminal"
    markdown = "markdown"
    json = "json"


@app.command("schema-watch")
def schema_watch_cmd(
    old_config: Annotated[Path, typer.Argument(help="Baseline config YAML")],
    new_config: Annotated[Path, typer.Argument(help="Candidate config YAML")],
    fmt: Annotated[
        SchemaWatchFormat,
        typer.Option("--format", "-f", help="Output format"),
    ] = SchemaWatchFormat.terminal,
    fail_on: Annotated[
        str,
        typer.Option(
            "--fail-on",
            help="Exit non-zero when a change of at least this severity is found. "
            "One of: breaking, risky, additive, neutral, none.",
        ),
    ] = "breaking",
) -> None:
    """Classify tool-schema changes between two configs without replaying.

    Cheap, proactive check for tool-schema regressions (renames, dropped
    required params, enum narrowing). Designed to run first in CI —
    before `shadow diff` — so PRs get a fast signal on whether any
    schema edits are agent-breaking.

    Exit code: 1 if any change at --fail-on severity or higher is
    detected; 0 otherwise.
    """
    from shadow.schema_watch import (
        Severity,
        render_markdown,
        render_terminal,
        watch_files,
    )

    severity_order = {
        "breaking": 0,
        "risky": 1,
        "additive": 2,
        "neutral": 3,
        "none": 99,
    }
    if fail_on not in severity_order:
        err_console.print(
            f"[red]error[/]: --fail-on must be one of " f"{', '.join(severity_order.keys())}"
        )
        raise typer.Exit(code=2)

    try:
        report = watch_files(old_config, new_config)
    except ShadowError as e:
        _fail(e)
        return
    except Exception as e:
        _fail(e)
        return

    if fmt is SchemaWatchFormat.terminal:
        console.print(render_terminal(report))
    elif fmt is SchemaWatchFormat.markdown:
        sys.stdout.write(render_markdown(report))
    else:
        sys.stdout.write(json.dumps(report.to_dict(), indent=2) + "\n")

    threshold = severity_order[fail_on]
    observed = {
        Severity.BREAKING: 0,
        Severity.RISKY: 1,
        Severity.ADDITIVE: 2,
        Severity.NEUTRAL: 3,
    }
    worst = min(
        (observed[c.severity] for c in report.changes),
        default=99,
    )
    if worst <= threshold:
        raise typer.Exit(code=1)


# ---- version (hidden convenience) -----------------------------------------


@app.command()
def version() -> None:
    """Print the installed shadow version."""
    console.print(f"shadow {__version__} (spec {_core.SPEC_VERSION})")


# ---- helpers ---------------------------------------------------------------


def _fail(e: BaseException) -> None:
    err_console.print(f"[bold red]error[/]: {e}")
    raise typer.Exit(code=1)


def main() -> None:
    """Entry point registered as the `shadow` console_script."""
    app()


if __name__ == "__main__":
    main()
