"""Typer-based CLI for shadow."""

from __future__ import annotations

import asyncio
import json
import os
import subprocess
import sys
from enum import StrEnum
from pathlib import Path
from typing import Annotated, Any

import typer
import yaml
from rich.console import Console

from shadow import __version__, _core
from shadow.errors import ShadowError

app = typer.Typer(
    name="shadow",
    help="Git-native behavioral diff and shadow deployment for LLM agents.",
    no_args_is_help=True,
    add_completion=False,
)

console = Console(stderr=False)
err_console = Console(stderr=True)


# ---- init ------------------------------------------------------------------

DEFAULT_CONFIG_TOML = """# .shadow/config.toml — generated by `shadow init`.
# See SPEC.md §8 for what this controls.

[store]
# Where traces and the SQLite index live, relative to the repo root.
path = ".shadow"

[replay]
# Default backend when `--backend` is not specified.
default_backend = "mock"
"""


GITHUB_ACTION_WORKFLOW = """\
# .github/workflows/shadow-diff.yml — generated by `shadow init --github-action`
#
# Runs Shadow's nine-axis behavioural diff on every pull request and
# posts the result as a PR comment. Edit the `BASELINE` / `CANDIDATE`
# paths to point at trace fixtures you commit in your repo.
name: shadow diff

on:
  pull_request:
    paths:
      # Re-run whenever an agent config or committed trace changes.
      # Add globs for your own layout as needed.
      - "configs/**"
      - "fixtures/**.agentlog"
      - ".github/workflows/shadow-diff.yml"

permissions:
  pull-requests: write  # required to post the diff comment
  contents: read

jobs:
  diff:
    name: shadow behavioural diff
    runs-on: ubuntu-latest
    env:
      # Edit these two paths to point at your committed fixtures.
      BASELINE: fixtures/baseline.agentlog
      CANDIDATE: fixtures/candidate.agentlog
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install shadow-diff
        run: pip install --upgrade "shadow-diff>=1.2,<2"

      - name: Compute diff
        run: |
          shadow diff "$BASELINE" "$CANDIDATE" \\
            --output-json diff.json \\
            || true  # diff can exit non-zero on severe regression; we still want the comment

      - name: Render PR comment
        run: shadow report diff.json --format github-pr > comment.md

      - name: Post comment on PR
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr comment "${{ github.event.pull_request.number }}" --body-file comment.md
"""


@app.command()
def init(
    path: Annotated[Path, typer.Argument(help="Project root (defaults to cwd)")] = Path("."),
    github_action: Annotated[
        bool,
        typer.Option(
            "--github-action",
            help="Also scaffold `.github/workflows/shadow-diff.yml` — a pre-wired "
            "GitHub Actions workflow that runs `shadow diff` on every PR and "
            "posts the result as a comment.",
        ),
    ] = False,
) -> None:
    """Scaffold `.shadow/` in PATH. Creates dirs, config.toml, sqlite index.

    Pass `--github-action` to also drop a ready-to-commit GitHub
    Actions workflow under `.github/workflows/shadow-diff.yml`. Edit
    the `BASELINE` / `CANDIDATE` env vars in that file to point at
    your repo's committed trace fixtures, then git-commit and push —
    every PR will get a diff comment.
    """
    try:
        shadow_dir = path / ".shadow"
        (shadow_dir / "traces").mkdir(parents=True, exist_ok=True)
        (shadow_dir / "replays").mkdir(parents=True, exist_ok=True)
        (shadow_dir / "cache").mkdir(parents=True, exist_ok=True)
        config_path = shadow_dir / "config.toml"
        if not config_path.exists():
            config_path.write_text(DEFAULT_CONFIG_TOML)
        err_console.print(f"[green]✓[/] initialised shadow store at {shadow_dir}")

        if github_action:
            workflow_dir = path / ".github" / "workflows"
            workflow_dir.mkdir(parents=True, exist_ok=True)
            workflow_path = workflow_dir / "shadow-diff.yml"
            if workflow_path.exists():
                err_console.print(f"[yellow]·[/] {workflow_path} already exists — not overwritten.")
            else:
                workflow_path.write_text(GITHUB_ACTION_WORKFLOW)
                err_console.print(
                    f"[green]✓[/] wrote {workflow_path}\n"
                    "    edit BASELINE / CANDIDATE paths, commit, and every PR "
                    "will get a diff comment."
                )
    except Exception as e:
        _fail(e)


# ---- quickstart ------------------------------------------------------------


@app.command()
def quickstart(
    path: Annotated[
        Path,
        typer.Argument(help="Directory to scaffold into (created if missing)"),
    ] = Path("shadow-quickstart"),
    force: Annotated[
        bool,
        typer.Option(
            "--force",
            help="Overwrite files in PATH even if they already exist.",
        ),
    ] = False,
) -> None:
    """Scaffold a minimal runnable Shadow scenario in PATH.

    Drops a toy agent, two configs (differing on three known axes),
    and pre-recorded baseline + candidate `.agentlog` fixtures. A
    brand-new user can go from `pip install shadow-diff` to seeing
    a real nine-axis diff in under a minute, no API keys required.

    Example:
        shadow quickstart              # scaffolds into ./shadow-quickstart/
        shadow quickstart my-demo/     # scaffolds into ./my-demo/
        shadow quickstart --force      # overwrites existing files
    """
    from importlib import resources

    try:
        import shadow.quickstart_data as _qs_data
    except ImportError as e:  # pragma: no cover — wheel always ships this
        _fail(Exception(f"shadow[quickstart-data] missing from install: {e}"))
        return

    dest = path.resolve()
    # Path-traversal hardening: refuse to scaffold into a system
    # directory. Users should be able to `shadow quickstart ~/projects/foo/`
    # but not accidentally wipe `/etc/` via shell-expansion mishaps.
    forbidden_prefixes = ("/etc", "/usr", "/bin", "/sbin", "/boot", "/proc", "/sys", "/dev")
    if any(str(dest).startswith(p + "/") or str(dest) == p for p in forbidden_prefixes):
        _fail(Exception(f"refusing to scaffold into a system directory: {dest}"))
        return
    dest.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []
    skipped: list[Path] = []

    # Files to copy from the packaged quickstart_data resource. Two-level
    # list because `fixtures/` is a subdirectory. Keeps the copy logic
    # trivial — no need to recursively walk the package.
    plan: list[tuple[str, Path]] = [
        ("agent.py", dest / "agent.py"),
        ("config_a.yaml", dest / "config_a.yaml"),
        ("config_b.yaml", dest / "config_b.yaml"),
        ("README.md", dest / "QUICKSTART.md"),
    ]
    fixtures_dest = dest / "fixtures"
    fixtures_dest.mkdir(exist_ok=True)
    fixture_plan: list[tuple[str, Path]] = [
        ("baseline.agentlog", fixtures_dest / "baseline.agentlog"),
        ("candidate.agentlog", fixtures_dest / "candidate.agentlog"),
    ]

    root = resources.files(_qs_data)
    try:
        for resource_name, target in plan:
            if target.exists() and not force:
                skipped.append(target)
                continue
            target.write_bytes(root.joinpath(resource_name).read_bytes())
            written.append(target)
        for resource_name, target in fixture_plan:
            if target.exists() and not force:
                skipped.append(target)
                continue
            target.write_bytes(root.joinpath("fixtures").joinpath(resource_name).read_bytes())
            written.append(target)
    except Exception as e:
        _fail(e)
        return

    def _rel(p: Path) -> Path:
        return p.relative_to(Path.cwd()) if p.is_relative_to(Path.cwd()) else p

    for p in written:
        err_console.print(f"[green]✓[/] wrote {_rel(p)}")
    for p in skipped:
        err_console.print(
            f"[yellow]·[/] skipped {_rel(p)} (already exists; use --force to overwrite)"
        )

    if written:
        rel = _rel(dest)
        err_console.print("")
        err_console.print(f"[bold]Next steps[/] ({rel}/):")
        err_console.print(f"  1.  cd {rel}")
        err_console.print(
            "  2.  shadow diff fixtures/baseline.agentlog " "fixtures/candidate.agentlog"
        )
        err_console.print("")
        err_console.print("[dim]See QUICKSTART.md for how to record your own agent's traces.[/]")


# ---- record ----------------------------------------------------------------


@app.command(
    # Without these, Typer 0.24 treats the `--` separator as "end of
    # options" but still errors out on unrecognised positional args
    # after it. Explicit per-command allow_extra_args forwards the
    # tokens after `--` to ctx.args as raw strings.
    context_settings={"allow_extra_args": True, "ignore_unknown_options": True},
)
def record(
    ctx: typer.Context,
    output: Annotated[
        Path, typer.Option("--output", "-o", help="Where to write the .agentlog file")
    ] = Path("recording.agentlog"),
    tags: Annotated[
        str | None,
        typer.Option(
            "--tags",
            help="Comma-separated key=value tags for the trace metadata "
            "(e.g. --tags env=dev,branch=main).",
        ),
    ] = None,
    no_auto_instrument: Annotated[
        bool,
        typer.Option(
            "--no-auto-instrument",
            help="Disable zero-config instrumentation. Use this when the "
            "wrapped command already opens its own `Session` and you don't "
            "want a second one wrapping it.",
        ),
    ] = False,
) -> None:
    """Run a subcommand with zero-config auto-instrumentation.

    Example:
        shadow record -o demo.agentlog -- python agent.py

    The wrapped command's Python interpreter loads a sitecustomize
    shim that starts a `Session` around the whole process. Every
    `anthropic.*.messages.create` / `openai.*.chat.completions.create`
    call made by the agent gets recorded without the agent touching
    any Shadow code.

    If the wrapped command already imports `shadow.sdk.Session` on
    its own, pass `--no-auto-instrument` to avoid a double session.
    """
    args = ctx.args
    if not args:
        err_console.print("[red]error[/]: specify a command after `--`")
        raise typer.Exit(code=2)

    # Fail fast if the output path isn't writable. Catching this here —
    # before the agent runs — prevents wasting LLM API calls on a
    # recording that can't be saved.
    try:
        resolved = output.resolve()
        resolved.parent.mkdir(parents=True, exist_ok=True)
        # Probe actual writability (mkdir tolerates read-only parents
        # silently on some FSes; an open-for-append round-trips the real
        # permission check and leaves no partial bytes behind).
        with resolved.open("ab"):
            pass
        if resolved.stat().st_size == 0:
            # We just created the file via append; clean up so an empty
            # .agentlog doesn't mislead `shadow diff` later.
            resolved.unlink()
    except OSError as e:
        err_console.print(
            f"[red]error[/]: output path not writable: {output}\n"
            f"  reason: {e}\n"
            f"  hint: check the directory exists and you have write permission, "
            "then re-run."
        )
        raise typer.Exit(code=2) from None

    env = dict(os.environ)
    env["SHADOW_SESSION_OUTPUT"] = str(resolved)
    if tags:
        env["SHADOW_SESSION_TAGS"] = tags
    if not no_auto_instrument:
        # Prepend the bootstrap dir so our sitecustomize wins over any
        # other sitecustomize on the user's PYTHONPATH. Python's site.py
        # imports the first `sitecustomize` it finds on sys.path, so
        # prepending is the deterministic win.
        from shadow.sdk import _bootstrap

        bootstrap_dir = str(Path(_bootstrap.__file__).resolve().parent)
        existing = env.get("PYTHONPATH", "")
        env["PYTHONPATH"] = f"{bootstrap_dir}{os.pathsep}{existing}" if existing else bootstrap_dir
    result = subprocess.run(args, env=env, check=False)
    raise typer.Exit(code=result.returncode)


# allow `shadow record -- python agent.py` (trailing args)
# typer picks up ctx.args when the command is declared with allow_extra_args
app.info.context_settings = {"allow_extra_args": True, "ignore_unknown_options": True}


# ---- replay ----------------------------------------------------------------


class BackendKind(StrEnum):
    """Supported replay backends."""

    mock = "mock"
    positional = "positional"


class ToolBackendKind(StrEnum):
    """Tool backends for ``shadow replay --agent-loop``."""

    replay = "replay"
    stub = "stub"
    sandbox = "sandbox"


class NovelToolPolicyKind(StrEnum):
    """Behaviors for tool calls the baseline didn't record."""

    strict = "strict"
    stub = "stub"
    fuzzy = "fuzzy"


@app.command()
def replay(
    config_path: Annotated[Path, typer.Argument(help="Candidate config YAML")],
    baseline: Annotated[Path, typer.Option("--baseline", help="Baseline .agentlog file")],
    backend: Annotated[
        BackendKind, typer.Option("--backend", help="Backend to use")
    ] = BackendKind.mock,
    reference: Annotated[
        Path | None,
        typer.Option(
            "--reference",
            help="(positional backend only) candidate-recording to replay from",
        ),
    ] = None,
    output: Annotated[
        Path | None, typer.Option("--output", "-o", help="Where to write the candidate .agentlog")
    ] = None,
    partial: Annotated[
        bool,
        typer.Option(
            "--partial",
            help="Partial replay: lock turns 0..--branch-at to the baseline "
            "verbatim and replay only the suffix through the backend. "
            "Isolates behaviour change to a specific branch point — useful "
            "for 'if the agent took this path for 3 turns, what happens "
            "from turn 4 under config B?' experiments.",
        ),
    ] = False,
    branch_at: Annotated[
        int,
        typer.Option(
            "--branch-at",
            help="(with --partial) 0-based turn index where live replay "
            "begins. 0 = fully live (equivalent to the default replay).",
        ),
    ] = 0,
    agent_loop: Annotated[
        bool,
        typer.Option(
            "--agent-loop",
            help="Drive the candidate's agent loop forward instead of "
            "walking the baseline lock-step. Combine with --tool-backend "
            "to control how tool calls resolve. This is the 'shadow "
            "deployment' mode: candidate decides which tools to call, "
            "ToolBackend resolves them deterministically (or under "
            "sandbox), no real side effects.",
        ),
    ] = False,
    tool_backend: Annotated[
        ToolBackendKind,
        typer.Option(
            "--tool-backend",
            help="(with --agent-loop) how to resolve tool calls. "
            "'replay' uses the baseline's recorded results. 'stub' "
            "returns deterministic placeholders. 'sandbox' runs the "
            "user's real tool functions with side-effect isolation "
            "(requires programmatic API; CLI reserves the name).",
        ),
    ] = "replay",  # type: ignore[assignment]
    novel_tool_policy: Annotated[
        NovelToolPolicyKind,
        typer.Option(
            "--novel-tool-policy",
            help="(with --tool-backend replay) how to handle a "
            "candidate tool call the baseline never recorded. "
            "'strict' aborts the replay. 'stub' returns a placeholder. "
            "'fuzzy' matches the nearest same-tool call by arg shape.",
        ),
    ] = "stub",  # type: ignore[assignment]
    max_turns: Annotated[
        int,
        typer.Option(
            "--max-turns",
            help="(with --agent-loop) safety cap on agent-loop " "iterations per session.",
        ),
    ] = 32,
) -> None:
    """Replay BASELINE's requests through BACKEND, writing a candidate trace."""
    from shadow.llm import MockLLM, PositionalMockLLM
    from shadow.replay import run_partial_replay, run_replay

    try:
        # Validate the config is readable YAML (not used by Rust core in v0.1;
        # config-driven behavior-change lives in the candidate fixture/backend).
        yaml.safe_load(config_path.read_text())

        baseline_records = _core.parse_agentlog(baseline.read_bytes())
        if backend is BackendKind.mock:
            bk: Any = MockLLM.from_trace(baseline_records)
        else:
            if reference is None:
                err_console.print("[red]error[/]: --backend positional requires --reference <path>")
                raise typer.Exit(code=2)
            bk = PositionalMockLLM.from_path(reference)

        if agent_loop:
            from shadow.replay_loop import AgentLoopConfig, run_agent_loop_replay
            from shadow.tools.novel import (
                FuzzyMatchPolicy,
                StrictPolicy,
                StubPolicy,
            )
            from shadow.tools.replay import ReplayToolBackend
            from shadow.tools.stub import StubToolBackend

            policy_map: dict[str, Any] = {
                "strict": StrictPolicy(),
                "stub": StubPolicy(),
                "fuzzy": FuzzyMatchPolicy(),
            }
            policy = policy_map[str(novel_tool_policy)]

            if str(tool_backend) == "replay":
                tb: Any = ReplayToolBackend.from_trace(baseline_records, novel_policy=policy)
            elif str(tool_backend) == "stub":
                tb = StubToolBackend()
            elif str(tool_backend) == "sandbox":
                err_console.print(
                    "[red]error[/]: --tool-backend sandbox requires the "
                    "programmatic API (you must supply tool function "
                    "implementations). See "
                    "docs/features/sandboxed-replay.md."
                )
                raise typer.Exit(code=2)
            else:
                err_console.print(f"[red]error[/]: unknown --tool-backend {tool_backend!r}")
                raise typer.Exit(code=2)

            cfg = AgentLoopConfig(max_turns=max_turns)
            candidate, summary = asyncio.run(
                run_agent_loop_replay(
                    baseline_records,
                    llm_backend=bk,
                    tool_backend=tb,
                    config=cfg,
                )
            )
            out_path = output or _default_replay_output()
            out_path.parent.mkdir(parents=True, exist_ok=True)
            out_path.write_bytes(_core.write_agentlog(candidate))
            err_console.print(
                f"[green]✓[/] agent-loop replay written to {out_path} "
                f"({len(candidate)} records, "
                f"{summary.sessions_replayed} sessions, "
                f"{summary.total_llm_calls} LLM calls, "
                f"{summary.total_tool_calls} tool calls"
                + (
                    f", {summary.total_tool_errors} tool errors"
                    if summary.total_tool_errors
                    else ""
                )
                + ")"
            )
            return

        if partial:
            candidate = asyncio.run(run_partial_replay(baseline_records, branch_at, bk))
        else:
            candidate = asyncio.run(run_replay(baseline_records, bk))
        out_path = output or _default_replay_output()
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_bytes(_core.write_agentlog(candidate))
        err_console.print(f"[green]✓[/] replay written to {out_path} ({len(candidate)} records)")
    except ShadowError as e:
        _fail(e)
    except typer.Exit:
        raise
    except Exception as e:
        _fail(e)


def _default_replay_output() -> Path:
    return Path(".shadow/replays/latest.agentlog")


# ---- diff ------------------------------------------------------------------


class SemanticMode(StrEnum):
    """Semantic-axis backend for `shadow diff --semantic`."""

    bm25 = "bm25"
    embeddings = "embeddings"


class JudgeKind(StrEnum):
    """Judges available for the `diff --judge` flag.

    - `none` — skip axis 8 entirely. The Rust core emits a zero row.
    - `auto` — pick `sanity` + whichever backend has an API key in the
      env. ANTHROPIC_API_KEY is preferred (cheaper Haiku), then
      OPENAI_API_KEY (gpt-4o-mini). Falls through to `none` if
      neither is set.
    - `sanity`, `pairwise` — domain-agnostic; no config needed.
    - `llm`, `procedure`, `schema`, `factuality`, `refusal`, `tone` —
      need rubric data supplied via `--judge-config <file.yaml>`.
    """

    none = "none"
    auto = "auto"
    sanity = "sanity"
    pairwise = "pairwise"
    llm = "llm"
    procedure = "procedure"
    schema = "schema"
    factuality = "factuality"
    refusal = "refusal"
    tone = "tone"


class JudgeBackend(StrEnum):
    """LLM backends the SanityJudge can run against."""

    mock = "mock"
    anthropic = "anthropic"
    openai = "openai"


@app.command("diff")
def diff_cmd(
    baseline: Annotated[Path, typer.Argument(help="Baseline .agentlog file")],
    candidate: Annotated[Path, typer.Argument(help="Candidate .agentlog file")],
    pricing: Annotated[
        Path | None,
        typer.Option("--pricing", help="JSON pricing file (dict model→[in,out] USD/token)"),
    ] = None,
    seed: Annotated[int, typer.Option("--seed", help="RNG seed for bootstrap")] = 42,
    output_json: Annotated[
        Path | None,
        typer.Option("--output-json", help="Write DiffReport JSON to this path"),
    ] = None,
    semantic: Annotated[
        SemanticMode,
        typer.Option(
            "--semantic",
            help="Semantic-axis backend. `bm25` (default) = TF-IDF cosine; "
            "`embeddings` = sentence-transformers/all-MiniLM-L6-v2 (requires [embeddings] extra).",
        ),
    ] = SemanticMode.bm25,
    judge: Annotated[
        JudgeKind,
        typer.Option(
            "--judge",
            help="Populate axis 8 with a judge. `auto` picks `sanity` + whichever "
            "API-key env var is set (ANTHROPIC_API_KEY preferred). `sanity` / "
            "`pairwise` are domain-agnostic; `llm` / `procedure` / `schema` / "
            "`factuality` / `refusal` / `tone` need rubric data via "
            "--judge-config.",
        ),
    ] = JudgeKind.none,
    judge_backend: Annotated[
        JudgeBackend,
        typer.Option("--judge-backend", help="LLM backend the judge runs against"),
    ] = JudgeBackend.mock,
    judge_model: Annotated[
        str | None,
        typer.Option("--judge-model", help="Override the model name the judge uses"),
    ] = None,
    judge_config: Annotated[
        Path | None,
        typer.Option(
            "--judge-config",
            help="YAML file supplying judge rubric data. Required by judges other "
            "than `sanity` / `pairwise` / `auto`. See examples/judges/ for templates.",
        ),
    ] = None,
    explain: Annotated[
        bool,
        typer.Option(
            "--explain",
            help="After rendering the diff table, call an LLM to produce a one-"
            "paragraph plain-English summary of what changed, why it matters, "
            "and what to check first. Opt-in — requires a live backend + "
            "--judge-backend anthropic|openai (same keys auto-detected for "
            "--judge auto). ~300-500 tokens per run.",
        ),
    ] = False,
    hierarchical: Annotated[
        bool,
        typer.Option(
            "--hierarchical",
            help="Also print the session-level breakdown — one worst-severity "
            "line per conversation in the trace. Useful when the trace contains "
            "multiple user-facing conversations and you want to know which one "
            "regressed.",
        ),
    ] = False,
    token_breakdown: Annotated[
        bool,
        typer.Option(
            "--token-diff",
            help="Print the token-level distribution breakdown (input / output "
            "/ thinking tokens, median+p95+total per side, plus the top-k "
            "worst per-pair deltas). Complements the verbosity axis with "
            "structured numbers instead of a single severity roll-up.",
        ),
    ] = False,
    policy_file: Annotated[
        Path | None,
        typer.Option(
            "--policy",
            help="YAML/JSON policy overlay to check against both traces. A "
            "policy is a list of rules (must_call_before, no_call, "
            "max_turns, required_stop_reason, max_total_tokens, "
            "must_include_text, forbidden_text). Regressions (new "
            "violations in candidate) and fixes are reported.",
        ),
    ] = None,
    suggest_fixes_flag: Annotated[
        bool,
        typer.Option(
            "--suggest-fixes",
            help="Layer LLM-assisted code-level fix proposals on top of the "
            "deterministic recommendations. Requires a live backend (same "
            "selection rules as --judge-backend / --explain). Opt-in — "
            "~1-2k output tokens per diff depending on severity.",
        ),
    ] = False,
    fail_on: Annotated[
        str,
        typer.Option(
            "--fail-on",
            help="Exit non-zero when the worst axis severity or policy "
            "violation reaches this level. One of: never, minor, "
            "moderate, severe. Default: never (post the report and "
            "exit 0). Use `severe` to gate a PR merge on agent "
            "regressions.",
        ),
    ] = "never",
) -> None:
    """Compute a nine-axis diff between two traces and print the report."""
    from shadow.report import render_terminal

    try:
        b = _core.parse_agentlog(baseline.read_bytes())
        c = _core.parse_agentlog(candidate.read_bytes())
        price_map: dict[str, tuple[float, float]] | None = None
        if pricing is not None:
            raw = json.loads(pricing.read_text())
            price_map = _parse_pricing_table(raw)
        report = _core.compute_diff_report(b, c, price_map, seed)
        if semantic is SemanticMode.embeddings:
            report = _apply_embeddings_semantic(report, baseline=b, candidate=c, seed=seed)

        effective_judge, effective_backend = _resolve_auto_judge(judge, judge_backend)
        if effective_judge is not JudgeKind.none:
            report = _apply_judge(
                report,
                baseline_records=b,
                candidate_records=c,
                judge_kind=effective_judge,
                judge_backend=effective_backend,
                judge_model=judge_model,
                judge_config=judge_config,
                seed=seed,
            )

        render_terminal(report, console=console)

        # Deterministic plain-English summary — always runs, no LLM call.
        from shadow.report.summary import summarise_report

        summary = summarise_report(report)
        if summary:
            console.print("")
            console.print("[bold]What this means[/]")
            console.print(summary)

        # Session-cost attribution — always run, but only print when
        # the cost axis actually moved (otherwise pure noise on zero-
        # pricing traces). A PR-reviewer-friendly decomposition of
        # where the cost delta went.
        from shadow.cost_attribution import (
            attribute_cost,
        )
        from shadow.cost_attribution import (
            render_terminal as render_cost_terminal,
        )

        cost_report = attribute_cost(b, c, price_map or {})
        if abs(cost_report.total_delta_usd) > 1e-9:
            console.print("")
            console.print(render_cost_terminal(cost_report))

        # Session-level hierarchical breakdown — opt-in because on
        # single-session traces it's redundant with the top-level
        # severity row.
        if hierarchical:
            from shadow.hierarchical import diff_by_session, render_session_summary

            sessions = diff_by_session(b, c, price_map, seed)
            rollup = render_session_summary(sessions)
            if rollup:
                console.print("")
                console.print(rollup)

        if token_breakdown:
            from shadow.hierarchical import render_token_diff, token_diff

            t_diff = token_diff(b, c)
            console.print("")
            console.print(render_token_diff(t_diff))

        if policy_file is not None:
            from shadow.hierarchical import load_policy, policy_diff, render_policy_diff

            raw_policy: Any
            if policy_file.suffix.lower() in (".yaml", ".yml"):
                raw_policy = yaml.safe_load(policy_file.read_text())
            else:
                raw_policy = json.loads(policy_file.read_text())
            rules = load_policy(raw_policy)
            p_diff = policy_diff(b, c, rules)
            console.print("")
            console.print(render_policy_diff(p_diff))

        if suggest_fixes_flag:
            if effective_backend is JudgeBackend.mock:
                err_console.print(
                    "[yellow]warning[/]: --suggest-fixes requires a live backend. "
                    "Set --judge-backend anthropic|openai (or export "
                    "ANTHROPIC_API_KEY / OPENAI_API_KEY and use --judge auto)."
                )
            else:
                from shadow.llm import get_backend
                from shadow.suggest_fixes import (
                    render_terminal as render_suggest_terminal,
                )
                from shadow.suggest_fixes import suggest_fixes

                try:
                    backend = get_backend(effective_backend.value)
                    result = suggest_fixes(report, b, c, backend, model=judge_model)
                    console.print("")
                    console.print(render_suggest_terminal(result))
                except ShadowError as e:
                    err_console.print(f"[yellow]warning[/]: --suggest-fixes failed: {e}")
                except Exception as e:
                    err_console.print(f"[yellow]warning[/]: --suggest-fixes call failed: {e}")

        if explain:
            if effective_backend is JudgeBackend.mock:
                err_console.print(
                    "[yellow]warning[/]: --explain requested but --judge-backend is "
                    "mock. Set --judge-backend anthropic|openai (or export "
                    "ANTHROPIC_API_KEY / OPENAI_API_KEY and use --judge auto) "
                    "for a real explanation."
                )
            else:
                narrative = _generate_explanation(
                    report, backend_name=effective_backend.value, model=judge_model
                )
                if narrative:
                    console.print("")
                    console.print("[bold]Explain[/]")
                    console.print(narrative)

        if output_json is not None:
            output_json.parent.mkdir(parents=True, exist_ok=True)
            output_json.write_text(json.dumps(report, indent=2))

        # Merge-gate: exit non-zero when the worst signal exceeds the
        # caller's --fail-on threshold. The PR comment / output JSON
        # are still produced first; the failure is a separate concern.
        diff_rank = {"none": 0, "minor": 1, "moderate": 2, "severe": 3}
        policy_rank = {"info": 1, "warning": 2, "error": 3}
        fail_on_rank = {"never": 99, "minor": 1, "moderate": 2, "severe": 3}
        threshold = fail_on_rank.get(fail_on)
        if threshold is None:
            valid = ", ".join(k for k in fail_on_rank if k != "never")
            err_console.print(f"[red]error[/]: --fail-on must be one of {valid}, never")
            raise typer.Exit(code=2)
        if threshold < 99:
            rows = report.get("rows") or []
            worst_axis = max(
                (diff_rank.get(r.get("severity", "none"), 0) for r in rows),
                default=0,
            )
            worst_policy = 0
            if policy_file is not None:
                # p_diff was computed in the policy block above when
                # policy_file is set; recompute defensively here so the
                # gate works even if that block changed shape.
                from shadow.hierarchical import load_policy as _load_policy
                from shadow.hierarchical import policy_diff as _policy_diff

                _raw: Any
                if policy_file.suffix.lower() in (".yaml", ".yml"):
                    _raw = yaml.safe_load(policy_file.read_text())
                else:
                    _raw = json.loads(policy_file.read_text())
                _rules = _load_policy(_raw)
                _gate_diff = _policy_diff(b, c, _rules)
                # Regressions count toward the gate; fixes do not.
                for v in getattr(_gate_diff, "regressions", []) or []:
                    sev = getattr(v, "severity", "info")
                    worst_policy = max(worst_policy, policy_rank.get(sev, 1))
            worst = max(worst_axis, worst_policy)
            if worst >= threshold:
                err_console.print(
                    f"[red]fail[/]: worst signal severity {worst} >= "
                    f"--fail-on threshold {fail_on} ({threshold}); "
                    f"exiting 1 to gate the merge."
                )
                raise typer.Exit(code=1)
    except typer.Exit:
        raise
    except ShadowError as e:
        _fail(e)
    except Exception as e:
        _fail(e)


def _resolve_auto_judge(judge: JudgeKind, backend: JudgeBackend) -> tuple[JudgeKind, JudgeBackend]:
    """Expand `--judge auto` into a concrete (judge, backend) pair.

    Preference order is ANTHROPIC_API_KEY (cheaper Haiku 4.5) then
    OPENAI_API_KEY (gpt-4o-mini). If neither is set we quietly fall
    through to `none` — never silently skip for user-selected values.
    """
    if judge is not JudgeKind.auto:
        return judge, backend

    if os.environ.get("ANTHROPIC_API_KEY"):
        err_console.print(
            "[dim]judge: auto -> sanity on anthropic " "(Claude Haiku 4.5, ~$0.0003 per diff).[/]"
        )
        return JudgeKind.sanity, JudgeBackend.anthropic
    if os.environ.get("OPENAI_API_KEY"):
        err_console.print(
            "[dim]judge: auto -> sanity on openai " "(gpt-4o-mini, ~$0.0003 per diff).[/]"
        )
        return JudgeKind.sanity, JudgeBackend.openai
    err_console.print(
        "[dim]judge: auto requested but no ANTHROPIC_API_KEY or OPENAI_API_KEY "
        "found; axis 8 stays empty. Set either env var and re-run for a "
        "one-cent signal.[/]"
    )
    return JudgeKind.none, backend


def _generate_explanation(report: dict[str, Any], *, backend_name: str, model: str | None) -> str:
    """One-paragraph plain-English summary via the judge backend."""
    from shadow.llm import get_backend
    from shadow.report.summary import summarise_report

    determ = summarise_report(report)
    prompt = (
        "You are reviewing a Shadow behavioural diff between a baseline and a "
        "candidate agent trace. The deterministic summary below is the raw "
        "signal. Restate it for a tech lead in one short paragraph: what "
        "regressed, by how much, and the single highest-priority thing to "
        "verify. No pleasantries, no hedging, no preamble. <= 80 words.\n\n"
        f"Deterministic summary:\n{determ}"
    )
    backend = get_backend(backend_name)
    request: dict[str, Any] = {
        "model": model or "",
        "messages": [{"role": "user", "content": prompt}],
        "params": {"temperature": 0.0, "max_tokens": 256},
    }
    try:
        response = asyncio.run(backend.complete(request))
    except Exception as e:
        err_console.print(f"[yellow]warning[/]: --explain call failed: {e}")
        return ""
    content = response.get("content") or []
    if isinstance(content, str):
        return content.strip()
    parts: list[str] = []
    for part in content:
        if isinstance(part, dict) and part.get("type") == "text":
            text = part.get("text")
            if isinstance(text, str):
                parts.append(text)
    return "\n".join(parts).strip()


def _parse_pricing_table(raw: dict[str, Any]) -> dict[str, Any]:
    """Accept either legacy [input, output] tuple form or rich dict form.

    Rich form:
        "claude-opus-4-7": {
            "input": 0.000015,
            "output": 0.000075,
            "cached_input": 0.0000015,
            "reasoning": 0.0,
            "batch_discount": 0.5
        }
    """
    out: dict[str, Any] = {}
    for model, value in raw.items():
        if isinstance(value, list | tuple) and len(value) == 2:
            out[model] = (float(value[0]), float(value[1]))
        elif isinstance(value, dict):
            out[model] = {
                "input": float(value.get("input", 0.0)),
                "output": float(value.get("output", 0.0)),
                "cached_input": float(value.get("cached_input", 0.0)),
                "cached_write_5m": float(value.get("cached_write_5m", 0.0)),
                "cached_write_1h": float(value.get("cached_write_1h", 0.0)),
                "reasoning": float(value.get("reasoning", 0.0)),
                "batch_discount": float(value.get("batch_discount", 0.0)),
            }
        else:
            raise ShadowError(f"pricing entry for {model!r} must be [input, output] or a dict")
    return out


def _apply_embeddings_semantic(
    report: dict[str, Any],
    *,
    baseline: list[dict[str, Any]],
    candidate: list[dict[str, Any]],
    seed: int,
) -> dict[str, Any]:
    """Swap axis 1 (semantic) with a real sentence-transformer result."""
    try:
        from shadow.embeddings import SemanticEmbedder, recompute_semantic_axis
    except ImportError:
        err_console.print(
            "[yellow]warning[/]: --semantic embeddings requested but "
            "`shadow[embeddings]` isn't installed; falling back to BM25."
        )
        return report
    try:
        embedder = SemanticEmbedder()
    except ShadowError as e:
        err_console.print(f"[yellow]warning[/]: {e}; falling back to BM25.")
        return report
    new_row = recompute_semantic_axis(baseline, candidate, embedder, seed=seed)
    new_rows = [new_row if r.get("axis") == "semantic" else r for r in report.get("rows", [])]
    return {**report, "rows": new_rows}


def _apply_judge(
    report: dict[str, Any],
    *,
    baseline_records: list[dict[str, Any]],
    candidate_records: list[dict[str, Any]],
    judge_kind: JudgeKind,
    judge_backend: JudgeBackend,
    judge_model: str | None,
    judge_config: Path | None,
    seed: int,
) -> dict[str, Any]:
    from shadow.judge import aggregate_scores
    from shadow.llm import get_backend

    pairs = _pair_responses(baseline_records, candidate_records)
    if not pairs:
        return report

    backend = get_backend(judge_backend.value)
    cfg = _load_judge_config(judge_config) if judge_config is not None else {}
    judge_obj = _build_judge(judge_kind, backend, judge_model, cfg)

    async def _run() -> list[float]:
        out: list[float] = []
        for b_resp, c_resp, req_ctx in pairs:
            verdict = await judge_obj.score_pair(b_resp, c_resp, req_ctx)
            out.append(verdict["score"])
        return out

    scores = asyncio.run(_run())
    new_row = aggregate_scores(scores, seed=seed)
    new_rows = [new_row if r.get("axis") == "judge" else r for r in report.get("rows", [])]
    return {**report, "rows": new_rows}


def _load_judge_config(path: Path) -> dict[str, Any]:
    """Parse the --judge-config YAML file."""
    raw = yaml.safe_load(path.read_text())
    if not isinstance(raw, dict):
        raise ShadowError(
            f"--judge-config {path} must be a YAML mapping (got {type(raw).__name__})"
        )
    return raw


def _build_judge(
    kind: JudgeKind,
    backend: Any,
    model: str | None,
    cfg: dict[str, Any],
) -> Any:
    """Construct a Judge instance based on `--judge <kind>` + config data."""
    from shadow.judge import (
        FactualityJudge,
        LlmJudge,
        PairwiseJudge,
        ProcedureAdherenceJudge,
        RefusalAppropriateJudge,
        SanityJudge,
        SchemaConformanceJudge,
        ToneJudge,
    )

    def _require(key: str) -> Any:
        if key not in cfg:
            raise ShadowError(f"--judge {kind.value} requires '{key}' in --judge-config")
        return cfg[key]

    if kind is JudgeKind.sanity:
        return SanityJudge(backend, model=model)
    if kind is JudgeKind.pairwise:
        return PairwiseJudge(backend, model=model)
    if kind is JudgeKind.llm:
        return LlmJudge(
            backend,
            rubric=_require("rubric"),
            score_map=cfg.get("score_map"),
            model=model,
        )
    if kind is JudgeKind.procedure:
        return ProcedureAdherenceJudge(
            backend, required_procedure=_require("required_procedure"), model=model
        )
    if kind is JudgeKind.schema:
        return SchemaConformanceJudge(
            backend, expected_schema=_require("expected_schema"), model=model
        )
    if kind is JudgeKind.factuality:
        return FactualityJudge(backend, known_facts=_require("known_facts"), model=model)
    if kind is JudgeKind.refusal:
        return RefusalAppropriateJudge(backend, policy=_require("policy"), model=model)
    if kind is JudgeKind.tone:
        return ToneJudge(backend, target_tone=_require("target_tone"), model=model)
    raise ShadowError(f"unsupported --judge kind: {kind}")


def _pair_responses(
    baseline_records: list[dict[str, Any]],
    candidate_records: list[dict[str, Any]],
) -> list[tuple[dict[str, Any], dict[str, Any], dict[str, Any] | None]]:
    """Pair the i-th chat_response from baseline with the i-th from candidate.

    Each tuple also carries the baseline chat_request that preceded it (if
    any) so the judge has task context.
    """
    b_resps: list[dict[str, Any]] = []
    b_reqs_before: list[dict[str, Any] | None] = []
    last_req: dict[str, Any] | None = None
    for r in baseline_records:
        kind = r.get("kind")
        if kind == "chat_request":
            last_req = r.get("payload")
        elif kind == "chat_response":
            b_resps.append(r.get("payload") or {})
            b_reqs_before.append(last_req)
    c_resps: list[dict[str, Any]] = [
        r.get("payload") or {} for r in candidate_records if r.get("kind") == "chat_response"
    ]
    paired: list[tuple[dict[str, Any], dict[str, Any], dict[str, Any] | None]] = []
    for i in range(min(len(b_resps), len(c_resps))):
        paired.append((b_resps[i], c_resps[i], b_reqs_before[i]))
    return paired


# ---- bisect ----------------------------------------------------------------


class BisectBackend(StrEnum):
    """Backends available for live-replay corner bisection."""

    none = "none"
    anthropic = "anthropic"
    openai = "openai"
    positional = "positional"


class BisectFormat(StrEnum):
    """Output formats for `shadow bisect`."""

    terminal = "terminal"
    markdown = "markdown"
    json = "json"


@app.command()
def bisect(
    config_a: Annotated[Path, typer.Argument(help="Baseline config YAML")],
    config_b: Annotated[Path, typer.Argument(help="Candidate config YAML")],
    traces: Annotated[Path, typer.Option("--traces", help="Baseline .agentlog trace or dir")],
    candidate_traces: Annotated[
        Path | None,
        typer.Option(
            "--candidate-traces",
            help=(
                "Candidate .agentlog trace recorded under config_b. Used for "
                "the heuristic allocator when --backend is none."
            ),
        ),
    ] = None,
    backend: Annotated[
        BisectBackend,
        typer.Option(
            "--backend",
            help=(
                "Live backend for LASSO-over-corners scoring. 'anthropic' / "
                "'openai' require the corresponding extras and an API key. "
                "'positional' replays from a reference trace. 'none' falls "
                "back to --candidate-traces heuristic."
            ),
        ),
    ] = BisectBackend.none,
    reference: Annotated[
        Path | None,
        typer.Option(
            "--reference",
            help="(positional backend only) reference .agentlog for replay.",
        ),
    ] = None,
    output_json: Annotated[
        Path | None, typer.Option("--output-json", help="Write attribution JSON here")
    ] = None,
    fmt: Annotated[
        BisectFormat,
        typer.Option(
            "--format",
            "-f",
            help=(
                "Output format. `terminal` (default) prints a hedged human-"
                "readable summary. `markdown` emits a table for PR comments. "
                "`json` dumps the raw attribution dict — use this for "
                "scripts; everything else uses the renderer that softens "
                "'74.9% caused' into 'est. 74.9% (correlational, not "
                "causally proven; confirm with `shadow replay`)'."
            ),
        ),
    ] = BisectFormat.terminal,
) -> None:
    """Rank which atomic config deltas caused which behavioral axes to move."""
    try:
        from shadow.bisect import run_bisect
        from shadow.bisect.render import (
            render_attribution_markdown,
            render_attribution_terminal,
        )
    except ImportError as e:
        _fail(
            Exception(
                f"shadow.bisect failed to import ({e}); install with `pip install shadow[dev]`"
            )
        )
        return

    live_backend = None
    if backend is not BisectBackend.none:
        from shadow.llm import get_backend

        kwargs: dict[str, Any] = {}
        if backend is BisectBackend.positional:
            if reference is None:
                err_console.print("[red]error[/]: --backend positional requires --reference <path>")
                raise typer.Exit(code=2)
            kwargs["reference_path"] = reference
        try:
            live_backend = get_backend(backend.value, **kwargs)
        except ShadowError as e:
            _fail(e)
            return

    try:
        result = run_bisect(
            config_a,
            config_b,
            traces,
            candidate_traces=candidate_traces,
            backend=live_backend,
        )
        json_text = json.dumps(_json_safe(result), indent=2)
        if output_json is not None:
            output_json.parent.mkdir(parents=True, exist_ok=True)
            output_json.write_text(json_text)
        if fmt is BisectFormat.json:
            if output_json is None:
                sys.stdout.write(json_text + "\n")
        elif fmt is BisectFormat.markdown:
            sys.stdout.write(render_attribution_markdown(_json_safe(result)))
        else:
            sys.stdout.write(render_attribution_terminal(_json_safe(result)))
    except ShadowError as e:
        _fail(e)
    except Exception as e:
        _fail(e)


def _json_safe(obj: Any) -> Any:
    """Recursively strip non-JSON values from a dict (e.g. numpy arrays)."""
    import numpy as np

    if isinstance(obj, dict):
        return {k: _json_safe(v) for k, v in obj.items()}
    if isinstance(obj, list):
        return [_json_safe(v) for v in obj]
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    if isinstance(obj, np.integer | np.floating):
        return obj.item()
    return obj


# ---- report ----------------------------------------------------------------


class ReportFormat(StrEnum):
    """Supported report render formats."""

    terminal = "terminal"
    markdown = "markdown"
    github_pr = "github-pr"


@app.command()
def report(
    input_json: Annotated[Path, typer.Argument(help="DiffReport JSON file")],
    fmt: Annotated[
        ReportFormat, typer.Option("--format", "-f", help="Output format")
    ] = ReportFormat.terminal,
) -> None:
    """Re-render a saved DiffReport JSON."""
    from shadow.report import render_github_pr, render_markdown, render_terminal

    try:
        data = json.loads(input_json.read_text())
        if fmt is ReportFormat.terminal:
            render_terminal(data, console=console)
        elif fmt is ReportFormat.markdown:
            sys.stdout.write(render_markdown(data))
        else:
            sys.stdout.write(render_github_pr(data))
    except Exception as e:
        _fail(e)


# ---- join -----------------------------------------------------------------


@app.command()
def join(
    inputs: Annotated[
        list[Path], typer.Argument(help="Input .agentlog files to merge", metavar="INPUTS...")
    ],
    output: Annotated[Path, typer.Option("--output", "-o", help="Merged output path")],
) -> None:
    """Merge multiple `.agentlog` files (one per Session) into one logical trace.

    Records must carry `meta.trace_id` so we can group them; Sessions
    started under the same `SHADOW_TRACE_ID` env var share one. Parent
    links across files are rewired so the merged log is a single DAG.
    """
    try:
        all_records: list[dict[str, Any]] = []
        for p in inputs:
            all_records.extend(_core.parse_agentlog(p.read_bytes()))
        merged = _merge_by_trace(all_records)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_bytes(_core.write_agentlog(merged))
        err_console.print(
            f"[green]✓[/] merged {len(inputs)} file(s), {len(merged)} records → {output}"
        )
    except Exception as e:
        _fail(e)


def _merge_by_trace(records: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """Group by trace_id; chain parent-span records before their children."""
    by_trace: dict[str, list[dict[str, Any]]] = {}
    orphans: list[dict[str, Any]] = []
    for r in records:
        tid = (r.get("meta") or {}).get("trace_id")
        if tid is None:
            orphans.append(r)
        else:
            by_trace.setdefault(str(tid), []).append(r)
    out: list[dict[str, Any]] = []
    # Orphans first (no trace context), then per-trace groups in
    # arrival order to keep output deterministic.
    out.extend(orphans)
    for tid in sorted(by_trace.keys()):
        # Within a trace: sort by timestamp to preserve causality.
        group = sorted(by_trace[tid], key=lambda r: r.get("ts", ""))
        out.extend(group)
    return out


# ---- import ---------------------------------------------------------------


class ImportFormat(StrEnum):
    """Formats `shadow import` can read."""

    langfuse = "langfuse"
    braintrust = "braintrust"
    otel = "otel"
    langsmith = "langsmith"
    openai_evals = "openai-evals"
    mcp = "mcp"
    vercel_ai = "vercel-ai"
    pydantic_ai = "pydantic-ai"
    a2a = "a2a"


@app.command("import")
def import_cmd(
    source: Annotated[Path, typer.Argument(help="Foreign-format export file (.json or .jsonl)")],
    fmt: Annotated[
        ImportFormat,
        typer.Option("--format", "-f", help="Source format"),
    ],
    output: Annotated[Path, typer.Option("--output", "-o", help="Output .agentlog path")],
) -> None:
    """Convert a Langfuse or Braintrust export into a Shadow `.agentlog`.

    Turns Shadow's open spec into a bridge format: if you've already
    instrumented with another observability tool, `shadow import` lets
    you run Shadow's differ over traces you already have.
    """
    from shadow.importers import (
        a2a_to_agentlog,
        braintrust_to_agentlog,
        langfuse_to_agentlog,
        langsmith_to_agentlog,
        mcp_to_agentlog,
        openai_evals_to_agentlog,
        otel_to_agentlog,
        pydantic_ai_to_agentlog,
        vercel_ai_to_agentlog,
    )

    try:
        text = source.read_text()
        if fmt is ImportFormat.langfuse:
            data = json.loads(text)
            records = langfuse_to_agentlog(data)
        elif fmt is ImportFormat.braintrust:
            rows = _parse_braintrust_input(text)
            records = braintrust_to_agentlog(rows)
        elif fmt is ImportFormat.otel:
            data = json.loads(text)
            records = otel_to_agentlog(data)
        elif fmt is ImportFormat.langsmith:
            data = json.loads(text)
            records = langsmith_to_agentlog(data)
        elif fmt is ImportFormat.openai_evals:
            rows = _parse_jsonl_or_array(text)
            records = openai_evals_to_agentlog(rows)
        elif fmt is ImportFormat.mcp:
            # MCP logs in the wild are three shapes:
            #   (a) JSONL — one JSON-RPC message per line (the
            #       common `mcp-server --log ...` output).
            #   (b) JSON array — an explicit `[msg, msg, ...]`,
            #       what MCP Inspector's "export session" produces.
            #   (c) Wrapped object — `{"messages": [...], ...}` —
            #       some tooling bundles messages with metadata.
            # Detection is two-stage to distinguish (c) from (a), because
            # both can start with `{`: we first try a full-file parse;
            # if that yields a dict we treat it as (c), otherwise fall
            # back to the line-by-line JSONL path.
            stripped = text.lstrip()
            if stripped.startswith("["):
                data = json.loads(text)
            elif stripped.startswith("{"):
                try:
                    parsed = json.loads(text)
                except json.JSONDecodeError:
                    parsed = None
                data = parsed if isinstance(parsed, dict) else _parse_jsonl_or_array(text, "MCP")
            else:
                data = _parse_jsonl_or_array(text, "MCP")
            records = mcp_to_agentlog(data)
        elif fmt is ImportFormat.vercel_ai:
            # Vercel AI SDK telemetry exports arrive as either an
            # OTLP-style `{spans: [...]}` object or the AI Observability
            # dashboard's `{events: [...]}` shape. Try full-file parse
            # first; fall back to JSONL (OTLP exporters sometimes emit
            # one span per line when a batch is broken up).
            stripped = text.lstrip()
            if stripped.startswith("["):
                data = json.loads(text)
            elif stripped.startswith("{"):
                try:
                    parsed = json.loads(text)
                except json.JSONDecodeError:
                    parsed = None
                data = (
                    parsed if isinstance(parsed, dict) else _parse_jsonl_or_array(text, "Vercel AI")
                )
            else:
                data = _parse_jsonl_or_array(text, "Vercel AI")
            records = vercel_ai_to_agentlog(data)
        elif fmt is ImportFormat.pydantic_ai:
            # PydanticAI's `all_messages_json()` emits a JSON array.
            # Logfire exports may wrap it under `{spans: [...]}`. The
            # importer accepts both — feed it whatever parses.
            stripped = text.lstrip()
            if stripped.startswith("[") or stripped.startswith("{"):
                data = json.loads(text)
            else:
                data = _parse_jsonl_or_array(text, "PydanticAI")
            records = pydantic_ai_to_agentlog(data)
        elif fmt is ImportFormat.a2a:
            # A2A session logs use the same JSON-RPC 2.0 shape family as
            # MCP. The importer accepts JSONL, JSON array, and wrapped
            # object forms.
            stripped = text.lstrip()
            if stripped.startswith("["):
                data = json.loads(text)
            elif stripped.startswith("{"):
                try:
                    parsed = json.loads(text)
                except json.JSONDecodeError:
                    parsed = None
                data = parsed if isinstance(parsed, dict) else _parse_jsonl_or_array(text, "A2A")
            else:
                data = _parse_jsonl_or_array(text, "A2A")
            records = a2a_to_agentlog(data)
        else:  # pragma: no cover — enum is exhaustive
            raise ValueError(f"unknown import format: {fmt}")
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_bytes(_core.write_agentlog(records))
        err_console.print(
            f"[green]✓[/] imported {len(records)} records from {fmt.value} → {output}"
        )
    except ShadowError as e:
        _fail(e)
    except Exception as e:
        _fail(e)


def _parse_braintrust_input(text: str) -> list[dict[str, Any]]:
    """Braintrust exports may be a JSON array or JSONL. Accept either."""
    return _parse_jsonl_or_array(text, "Braintrust")


def _parse_jsonl_or_array(text: str, label: str = "input") -> list[dict[str, Any]]:
    """Accept either a JSON array or newline-delimited JSON."""
    stripped = text.lstrip()
    if stripped.startswith("["):
        parsed = json.loads(text)
        if not isinstance(parsed, list):
            raise ShadowError(f"{label} JSON input must be an array of rows")
        return parsed
    rows: list[dict[str, Any]] = []
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            continue
        rows.append(json.loads(line))
    return rows


# ---- export ---------------------------------------------------------------


class ExportFormat(StrEnum):
    """Formats `shadow export` can emit."""

    otel = "otel"


@app.command()
def export(
    trace: Annotated[Path, typer.Argument(help="Input .agentlog file")],
    fmt: Annotated[
        ExportFormat, typer.Option("--format", "-f", help="Output format")
    ] = ExportFormat.otel,
    output: Annotated[
        Path | None, typer.Option("--output", "-o", help="Write to file (else stdout)")
    ] = None,
) -> None:
    """Export a Shadow `.agentlog` to a standard observability format.

    Currently ships `otel` — OpenTelemetry OTLP/JSON using the GenAI
    semantic conventions. Pipe into `otel-cli` or post to any collector's
    `/v1/traces` endpoint.
    """
    from shadow.otel import agentlog_to_otel

    try:
        records = _core.parse_agentlog(trace.read_bytes())
        if fmt is ExportFormat.otel:
            result = agentlog_to_otel(records)
        else:
            raise ValueError(f"unknown export format: {fmt}")
        payload = json.dumps(result, indent=2)
        if output is not None:
            output.parent.mkdir(parents=True, exist_ok=True)
            output.write_text(payload)
        else:
            sys.stdout.write(payload + "\n")
    except Exception as e:
        _fail(e)


# ---- serve ----------------------------------------------------------------


@app.command()
def serve(
    root: Annotated[str, typer.Option("--root", help="Shadow root dir to tail")] = ".shadow",
    host: Annotated[str, typer.Option("--host", help="Listen host")] = "127.0.0.1",
    port: Annotated[int, typer.Option("--port", help="Listen port")] = 8765,
) -> None:
    """Start the live diff dashboard (requires `shadow[serve]` extra)."""
    try:
        from shadow.serve import serve as _serve

        _serve(root=Path(root), host=host, port=port)
    except Exception as e:
        _fail(e)


# ---- schema-watch ---------------------------------------------------------


class SchemaWatchFormat(StrEnum):
    """Output formats for `shadow schema-watch`."""

    terminal = "terminal"
    markdown = "markdown"
    json = "json"


@app.command("schema-watch")
def schema_watch_cmd(
    old_config: Annotated[Path, typer.Argument(help="Baseline config YAML")],
    new_config: Annotated[Path, typer.Argument(help="Candidate config YAML")],
    fmt: Annotated[
        SchemaWatchFormat,
        typer.Option("--format", "-f", help="Output format"),
    ] = SchemaWatchFormat.terminal,
    fail_on: Annotated[
        str,
        typer.Option(
            "--fail-on",
            help="Exit non-zero when a change of at least this severity is found. "
            "One of: breaking, risky, additive, neutral, none.",
        ),
    ] = "breaking",
) -> None:
    """Classify tool-schema changes between two configs without replaying.

    Cheap, proactive check for tool-schema regressions (renames, dropped
    required params, enum narrowing). Designed to run first in CI —
    before `shadow diff` — so PRs get a fast signal on whether any
    schema edits are agent-breaking.

    Exit code: 1 if any change at --fail-on severity or higher is
    detected; 0 otherwise.
    """
    from shadow.schema_watch import (
        Severity,
        render_markdown,
        render_terminal,
        watch_files,
    )

    severity_order = {
        "breaking": 0,
        "risky": 1,
        "additive": 2,
        "neutral": 3,
        "none": 99,
    }
    if fail_on not in severity_order:
        err_console.print(
            f"[red]error[/]: --fail-on must be one of " f"{', '.join(severity_order.keys())}"
        )
        raise typer.Exit(code=2)

    try:
        report = watch_files(old_config, new_config)
    except ShadowError as e:
        _fail(e)
        return
    except Exception as e:
        _fail(e)
        return

    if fmt is SchemaWatchFormat.terminal:
        console.print(render_terminal(report))
    elif fmt is SchemaWatchFormat.markdown:
        sys.stdout.write(render_markdown(report))
    else:
        sys.stdout.write(json.dumps(report.to_dict(), indent=2) + "\n")

    threshold = severity_order[fail_on]
    observed = {
        Severity.BREAKING: 0,
        Severity.RISKY: 1,
        Severity.ADDITIVE: 2,
        Severity.NEUTRAL: 3,
    }
    worst = min(
        (observed[c.severity] for c in report.changes),
        default=99,
    )
    if worst <= threshold:
        raise typer.Exit(code=1)


# ---- mine -----------------------------------------------------------------


@app.command("mine")
def mine_cmd(
    traces: Annotated[
        list[Path],
        typer.Argument(
            help="One or more .agentlog files to mine for representative cases.",
        ),
    ],
    output: Annotated[
        Path, typer.Option("--output", "-o", help="Where to write the mined .agentlog")
    ],
    max_cases: Annotated[
        int,
        typer.Option(
            "--max-cases",
            help="Cap on total selected pairs (default 50).",
        ),
    ] = 50,
    per_cluster: Annotated[
        int,
        typer.Option(
            "--per-cluster",
            help="Cap on how many pairs to keep from each cluster (default 1).",
        ),
    ] = 1,
    pricing: Annotated[
        Path | None,
        typer.Option("--pricing", help="Optional pricing.json for cost-aware scoring."),
    ] = None,
) -> None:
    """Pick representative turn-pairs out of a production trace set.

    Clusters all chat_request/chat_response pairs by tool-sequence +
    stop_reason + verbosity and latency buckets, then picks the most
    interesting example from each cluster (errors, refusals, high
    cost, heavy reasoning, very short/long responses). Writes a new
    .agentlog containing just the selected turns.

    The result is a compact, representative fixture set suitable for
    running `shadow diff` in CI against every PR.
    """
    from shadow.mine import mine as do_mine

    try:
        parsed_traces = []
        for path in traces:
            parsed_traces.append(_core.parse_agentlog(path.read_bytes()))
        price_map: dict[str, Any] | None = None
        if pricing is not None:
            price_map = json.loads(pricing.read_text())
        result = do_mine(
            parsed_traces,
            max_cases=max_cases,
            per_cluster=per_cluster,
            pricing=price_map,
        )
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_bytes(_core.write_agentlog(result.to_agentlog()))
        err_console.print(
            f"[green]✓[/] mined {len(result.cases)} cases from "
            f"{result.total_input_pairs} pairs in "
            f"{result.clusters_found} clusters → {output}"
        )
    except ShadowError as e:
        _fail(e)
    except Exception as e:
        _fail(e)


# ---- mcp-serve ------------------------------------------------------------


@app.command("mcp-serve")
def mcp_serve() -> None:
    """Run Shadow as a Model Context Protocol server over stdio.

    Exposes Shadow's diff, policy, token-diff, schema-watch, and summary
    capabilities as MCP tools so any MCP client (Claude Desktop, Claude
    Code, Cursor, Zed, and others) can invoke them. Typical config in
    a client's mcpServers block:

        "shadow": { "command": "shadow", "args": ["mcp-serve"] }

    The server speaks stdio, which is the standard local transport for
    MCP. Runs until the client closes the connection.
    """
    try:
        from shadow.mcp_server import main as mcp_main
    except ImportError as e:
        err_console.print(
            "[red]error[/]: mcp package is not installed.\n"
            "hint: pip install 'shadow-diff[mcp]' (or pip install mcp)"
        )
        raise typer.Exit(code=1) from e
    mcp_main()


# ---- version (hidden convenience) -----------------------------------------


@app.command()
def version() -> None:
    """Print the installed shadow version."""
    console.print(f"shadow {__version__} (spec {_core.SPEC_VERSION})")


# ---- helpers ---------------------------------------------------------------


def _fail(e: BaseException) -> None:
    err_console.print(f"[bold red]error[/]: {e}")
    raise typer.Exit(code=1)


def _force_utf8_io() -> None:
    """Force stdout/stderr to UTF-8 so Rich's box-drawing + `⚠`/`✓`/`✗`
    glyphs don't crash on Windows' cp1252 default.

    PEP 597 suggests this for Python applications that emit non-ASCII
    by design. No-op on POSIX (already UTF-8 in >99% of real-world
    setups) and on Python 3.15+ where UTF-8 mode is the default.
    """
    for stream in (sys.stdout, sys.stderr):
        try:
            if hasattr(stream, "reconfigure"):
                stream.reconfigure(encoding="utf-8", errors="replace")
        except Exception:
            # Swallow: the CLI should still start even if we can't
            # rebind the stream (e.g. if it's been wrapped by a test
            # harness). Rich has its own fallback for un-encodable
            # characters.
            pass


def main() -> None:
    """Entry point registered as the `shadow` console_script."""
    _force_utf8_io()
    app()


if __name__ == "__main__":
    main()
