"""Typer-based CLI for shadow."""

from __future__ import annotations

import asyncio
import json
import os
import subprocess
import sys
from enum import Enum
from pathlib import Path
from typing import Annotated, Any

import typer
import yaml
from rich.console import Console

from shadow import __version__, _core
from shadow.errors import ShadowError

app = typer.Typer(
    name="shadow",
    help="Git-native behavioral diff and shadow deployment for LLM agents.",
    no_args_is_help=True,
    add_completion=False,
)

console = Console(stderr=False)
err_console = Console(stderr=True)


# ---- init ------------------------------------------------------------------

DEFAULT_CONFIG_TOML = """# .shadow/config.toml — generated by `shadow init`.
# See CLAUDE.md §Storage layout for what this controls.

[store]
# Where traces and the SQLite index live, relative to the repo root.
path = ".shadow"

[replay]
# Default backend when `--backend` is not specified.
default_backend = "mock"
"""


@app.command()
def init(
    path: Annotated[Path, typer.Argument(help="Project root (defaults to cwd)")] = Path("."),
) -> None:
    """Scaffold `.shadow/` in PATH. Creates dirs, config.toml, sqlite index."""
    try:
        shadow_dir = path / ".shadow"
        (shadow_dir / "traces").mkdir(parents=True, exist_ok=True)
        (shadow_dir / "replays").mkdir(parents=True, exist_ok=True)
        (shadow_dir / "cache").mkdir(parents=True, exist_ok=True)
        config_path = shadow_dir / "config.toml"
        if not config_path.exists():
            config_path.write_text(DEFAULT_CONFIG_TOML)
        err_console.print(f"[green]✓[/] initialised shadow store at {shadow_dir}")
    except Exception as e:
        _fail(e)


# ---- record ----------------------------------------------------------------


@app.command()
def record(
    ctx: typer.Context,
    output: Annotated[
        Path, typer.Option("--output", "-o", help="Where to write the .agentlog file")
    ] = Path("recording.agentlog"),
) -> None:
    """Run a subcommand with SHADOW_SESSION_OUTPUT pointing at OUTPUT.

    Example:
        shadow record -o demo.agentlog -- python agent.py

    The wrapped command is expected to use shadow.sdk.Session for
    recording; if it doesn't, this command is a no-op (exits with the
    child's exit code).
    """
    args = ctx.args
    if not args:
        err_console.print("[red]error[/]: specify a command after `--`")
        raise typer.Exit(code=2)
    env = dict(os.environ)
    env["SHADOW_SESSION_OUTPUT"] = str(output.resolve())
    result = subprocess.run(args, env=env, check=False)
    raise typer.Exit(code=result.returncode)


# allow `shadow record -- python agent.py` (trailing args)
# typer picks up ctx.args when the command is declared with allow_extra_args
app.info.context_settings = {"allow_extra_args": True, "ignore_unknown_options": True}


# ---- replay ----------------------------------------------------------------


class BackendKind(str, Enum):
    """Supported replay backends."""

    mock = "mock"
    positional = "positional"


@app.command()
def replay(
    config_path: Annotated[Path, typer.Argument(help="Candidate config YAML")],
    baseline: Annotated[Path, typer.Option("--baseline", help="Baseline .agentlog file")],
    backend: Annotated[
        BackendKind, typer.Option("--backend", help="Backend to use")
    ] = BackendKind.mock,
    reference: Annotated[
        Path | None,
        typer.Option(
            "--reference",
            help="(positional backend only) candidate-recording to replay from",
        ),
    ] = None,
    output: Annotated[
        Path | None, typer.Option("--output", "-o", help="Where to write the candidate .agentlog")
    ] = None,
) -> None:
    """Replay BASELINE's requests through BACKEND, writing a candidate trace."""
    from shadow.llm import MockLLM, PositionalMockLLM
    from shadow.replay import run_replay

    try:
        # Validate the config is readable YAML (not used by Rust core in v0.1;
        # config-driven behavior-change lives in the candidate fixture/backend).
        yaml.safe_load(config_path.read_text())

        baseline_records = _core.parse_agentlog(baseline.read_bytes())
        if backend is BackendKind.mock:
            bk: Any = MockLLM.from_trace(baseline_records)
        else:
            if reference is None:
                err_console.print("[red]error[/]: --backend positional requires --reference <path>")
                raise typer.Exit(code=2)
            bk = PositionalMockLLM.from_path(reference)
        candidate = asyncio.run(run_replay(baseline_records, bk))
        out_path = output or _default_replay_output()
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_bytes(_core.write_agentlog(candidate))
        err_console.print(f"[green]✓[/] replay written to {out_path} ({len(candidate)} records)")
    except ShadowError as e:
        _fail(e)
    except typer.Exit:
        raise
    except Exception as e:
        _fail(e)


def _default_replay_output() -> Path:
    return Path(".shadow/replays/latest.agentlog")


# ---- diff ------------------------------------------------------------------


@app.command("diff")
def diff_cmd(
    baseline: Annotated[Path, typer.Argument(help="Baseline .agentlog file")],
    candidate: Annotated[Path, typer.Argument(help="Candidate .agentlog file")],
    pricing: Annotated[
        Path | None,
        typer.Option("--pricing", help="JSON pricing file (dict model→[in,out] USD/token)"),
    ] = None,
    seed: Annotated[int, typer.Option("--seed", help="RNG seed for bootstrap")] = 42,
    output_json: Annotated[
        Path | None,
        typer.Option("--output-json", help="Write DiffReport JSON to this path"),
    ] = None,
) -> None:
    """Compute a nine-axis diff between two traces and print the report."""
    from shadow.report import render_terminal

    try:
        b = _core.parse_agentlog(baseline.read_bytes())
        c = _core.parse_agentlog(candidate.read_bytes())
        price_map: dict[str, tuple[float, float]] | None = None
        if pricing is not None:
            raw = json.loads(pricing.read_text())
            price_map = {k: (float(v[0]), float(v[1])) for k, v in raw.items()}
        report = _core.compute_diff_report(b, c, price_map, seed)
        render_terminal(report, console=console)
        if output_json is not None:
            output_json.parent.mkdir(parents=True, exist_ok=True)
            output_json.write_text(json.dumps(report, indent=2))
    except ShadowError as e:
        _fail(e)
    except Exception as e:
        _fail(e)


# ---- bisect ----------------------------------------------------------------


@app.command()
def bisect(
    config_a: Annotated[Path, typer.Argument(help="Baseline config YAML")],
    config_b: Annotated[Path, typer.Argument(help="Candidate config YAML")],
    traces: Annotated[Path, typer.Option("--traces", help=".agentlog trace or dir")],
    output_json: Annotated[
        Path | None, typer.Option("--output-json", help="Write attribution JSON here")
    ] = None,
) -> None:
    """Rank which atomic config deltas caused which behavioral axes to move."""
    try:
        from shadow.bisect import run_bisect
    except ImportError as e:
        _fail(
            Exception(
                f"shadow.bisect failed to import ({e}); install with `pip install shadow[dev]`"
            )
        )
        return
    try:
        result = run_bisect(config_a, config_b, traces)
        text = json.dumps(result, indent=2)
        if output_json is not None:
            output_json.parent.mkdir(parents=True, exist_ok=True)
            output_json.write_text(text)
        else:
            # Write unstyled JSON to stdout — callers pipe this into `jq` etc.
            sys.stdout.write(text + "\n")
    except ShadowError as e:
        _fail(e)
    except Exception as e:
        _fail(e)


# ---- report ----------------------------------------------------------------


class ReportFormat(str, Enum):
    """Supported report render formats."""

    terminal = "terminal"
    markdown = "markdown"
    github_pr = "github-pr"


@app.command()
def report(
    input_json: Annotated[Path, typer.Argument(help="DiffReport JSON file")],
    fmt: Annotated[
        ReportFormat, typer.Option("--format", "-f", help="Output format")
    ] = ReportFormat.terminal,
) -> None:
    """Re-render a saved DiffReport JSON."""
    from shadow.report import render_github_pr, render_markdown, render_terminal

    try:
        data = json.loads(input_json.read_text())
        if fmt is ReportFormat.terminal:
            render_terminal(data, console=console)
        elif fmt is ReportFormat.markdown:
            sys.stdout.write(render_markdown(data))
        else:
            sys.stdout.write(render_github_pr(data))
    except Exception as e:
        _fail(e)


# ---- version (hidden convenience) -----------------------------------------


@app.command()
def version() -> None:
    """Print the installed shadow version."""
    console.print(f"shadow {__version__} (spec {_core.SPEC_VERSION})")


# ---- helpers ---------------------------------------------------------------


def _fail(e: BaseException) -> None:
    err_console.print(f"[bold red]error[/]: {e}")
    raise typer.Exit(code=1)


def main() -> None:
    """Entry point registered as the `shadow` console_script."""
    app()


if __name__ == "__main__":
    main()
